/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.AdminSide;

import GUI.HMS_Demo;
import GUI.LoginPanel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Admin_Emp extends javax.swing.JPanel {

    /**
     * Creates new form Admin_Emp
     */
    public Admin_Emp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel1 = new GUI.CustomStyle.Panel();
        Admin_emp_left = new GUI.CustomStyle.Panel();
        sideBar_paint1 = new GUI.AdminSide.SideBar_paint();
        jLabel4 = new javax.swing.JLabel();
        btn_EmpAdminDoctors = new GUI.CustomStyle.MyButton();
        panel2 = new GUI.CustomStyle.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_EmpAdminReception = new GUI.CustomStyle.MyButton();
        jLabel7 = new javax.swing.JLabel();
        btn_EmpAdminMessage = new GUI.CustomStyle.MyButton();
        jLabel8 = new javax.swing.JLabel();
        btn_EmpAdminNotification = new GUI.CustomStyle.MyButton();
        jLabel9 = new javax.swing.JLabel();
        btn_EmpAdminChangePass = new GUI.CustomStyle.MyButton();
        jLabel3 = new javax.swing.JLabel();
        logoutButton = new GUI.CustomStyle.MyButton();
        btn_message1 = new GUI.CustomStyle.MyButton();
        jLabel10 = new javax.swing.JLabel();
        Admin_right_panel1 = new GUI.CustomStyle.Panel();
        Admin_Emp_jTabbedPane = new javax.swing.JTabbedPane();
        panel1 = new GUI.CustomStyle.Panel();
        admin_Emp_Doctors1 = new GUI.AdminSide.Admin_Emp_Doctors();
        panel3 = new GUI.CustomStyle.Panel();
        admin_Emp_Receptionists1 = new GUI.AdminSide.Admin_Emp_Receptionists();
        panel4 = new GUI.CustomStyle.Panel();
        admin_Messages2 = new GUI.AdminSide.Admin_Messages();
        panel6 = new GUI.CustomStyle.Panel();
        admin_Emp_Notification2 = new GUI.AdminSide.Admin_Emp_Notification();
        panel7 = new GUI.CustomStyle.Panel();
        admin_EmpPassword1 = new GUI.AdminSide.Admin_EmpPassword();

        setMinimumSize(new java.awt.Dimension(1180, 800));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1180, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel1.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        mainPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        mainPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admin_emp_left.setBackground(new java.awt.Color(0, 51, 51));
        Admin_emp_left.setToolTipText("");
        Admin_emp_left.setMinimumSize(new java.awt.Dimension(220, 790));
        Admin_emp_left.setName(""); // NOI18N
        Admin_emp_left.setOpaque(true);
        Admin_emp_left.setPreferredSize(new java.awt.Dimension(220, 790));
        Admin_emp_left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBar_paint1.setMinimumSize(new java.awt.Dimension(220, 750));
        sideBar_paint1.setPreferredSize(new java.awt.Dimension(220, 750));
        sideBar_paint1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doctor.png"))); // NOI18N
        sideBar_paint1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 40));

        btn_EmpAdminDoctors.setBackground(new java.awt.Color(153, 0, 153));
        btn_EmpAdminDoctors.setBorder(null);
        btn_EmpAdminDoctors.setForeground(new java.awt.Color(204, 255, 255));
        btn_EmpAdminDoctors.setText("Doctors");
        btn_EmpAdminDoctors.setAutoscrolls(true);
        btn_EmpAdminDoctors.setBorderColor(new java.awt.Color(153, 0, 153));
        btn_EmpAdminDoctors.setColor(new java.awt.Color(153, 0, 153));
        btn_EmpAdminDoctors.setColorClick(new java.awt.Color(77, 0, 102));
        btn_EmpAdminDoctors.setColorOver(new java.awt.Color(0, 132, 202));
        btn_EmpAdminDoctors.setFocusPainted(false);
        btn_EmpAdminDoctors.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_EmpAdminDoctors.setMargin(new java.awt.Insets(2, 2, 3, 14));
        btn_EmpAdminDoctors.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_EmpAdminDoctorsMouseMoved(evt);
            }
        });
        btn_EmpAdminDoctors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EmpAdminDoctorsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EmpAdminDoctorsMouseExited(evt);
            }
        });
        btn_EmpAdminDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmpAdminDoctorsActionPerformed(evt);
            }
        });
        sideBar_paint1.add(btn_EmpAdminDoctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, 40));

        panel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin-Employee");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/owner (1).png"))); // NOI18N

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        sideBar_paint1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 140));

        jLabel14.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 255));
        jLabel14.setText("My Data");
        sideBar_paint1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 60, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/receptionist.png"))); // NOI18N
        sideBar_paint1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 50, 40));

        btn_EmpAdminReception.setBackground(new java.awt.Color(153, 0, 153));
        btn_EmpAdminReception.setBorder(null);
        btn_EmpAdminReception.setForeground(new java.awt.Color(204, 255, 255));
        btn_EmpAdminReception.setText("Receptionists");
        btn_EmpAdminReception.setBorderColor(new java.awt.Color(153, 0, 153));
        btn_EmpAdminReception.setColor(new java.awt.Color(153, 0, 153));
        btn_EmpAdminReception.setColorClick(new java.awt.Color(77, 0, 102));
        btn_EmpAdminReception.setColorOver(new java.awt.Color(0, 132, 202));
        btn_EmpAdminReception.setFocusPainted(false);
        btn_EmpAdminReception.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_EmpAdminReception.setMargin(new java.awt.Insets(2, 2, 3, 14));
        btn_EmpAdminReception.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_EmpAdminReceptionMouseMoved(evt);
            }
        });
        btn_EmpAdminReception.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EmpAdminReceptionMouseExited(evt);
            }
        });
        btn_EmpAdminReception.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmpAdminReceptionActionPerformed(evt);
            }
        });
        sideBar_paint1.add(btn_EmpAdminReception, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/paper-plane.png"))); // NOI18N
        sideBar_paint1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 50, 40));

        btn_EmpAdminMessage.setBackground(new java.awt.Color(153, 0, 153));
        btn_EmpAdminMessage.setBorder(null);
        btn_EmpAdminMessage.setForeground(new java.awt.Color(204, 255, 255));
        btn_EmpAdminMessage.setText("Messages");
        btn_EmpAdminMessage.setBorderColor(new java.awt.Color(153, 0, 153));
        btn_EmpAdminMessage.setColor(new java.awt.Color(153, 0, 153));
        btn_EmpAdminMessage.setColorClick(new java.awt.Color(77, 0, 102));
        btn_EmpAdminMessage.setColorOver(new java.awt.Color(0, 132, 202));
        btn_EmpAdminMessage.setFocusPainted(false);
        btn_EmpAdminMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_EmpAdminMessage.setMargin(new java.awt.Insets(2, 2, 3, 14));
        btn_EmpAdminMessage.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_EmpAdminMessageMouseMoved(evt);
            }
        });
        btn_EmpAdminMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EmpAdminMessageMouseExited(evt);
            }
        });
        btn_EmpAdminMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmpAdminMessageActionPerformed(evt);
            }
        });
        sideBar_paint1.add(btn_EmpAdminMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/notification.png"))); // NOI18N
        sideBar_paint1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 50, 40));

        btn_EmpAdminNotification.setBackground(new java.awt.Color(153, 0, 153));
        btn_EmpAdminNotification.setBorder(null);
        btn_EmpAdminNotification.setForeground(new java.awt.Color(204, 255, 255));
        btn_EmpAdminNotification.setText(" Notification");
        btn_EmpAdminNotification.setBorderColor(new java.awt.Color(153, 0, 153));
        btn_EmpAdminNotification.setColor(new java.awt.Color(153, 0, 153));
        btn_EmpAdminNotification.setColorClick(new java.awt.Color(77, 0, 102));
        btn_EmpAdminNotification.setColorOver(new java.awt.Color(0, 132, 202));
        btn_EmpAdminNotification.setFocusPainted(false);
        btn_EmpAdminNotification.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_EmpAdminNotification.setMargin(new java.awt.Insets(2, 2, 3, 14));
        btn_EmpAdminNotification.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_EmpAdminNotificationMouseMoved(evt);
            }
        });
        btn_EmpAdminNotification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EmpAdminNotificationMouseExited(evt);
            }
        });
        btn_EmpAdminNotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmpAdminNotificationActionPerformed(evt);
            }
        });
        sideBar_paint1.add(btn_EmpAdminNotification, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 220, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/padlock.png"))); // NOI18N
        sideBar_paint1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, 40));

        btn_EmpAdminChangePass.setBackground(new java.awt.Color(153, 0, 153));
        btn_EmpAdminChangePass.setBorder(null);
        btn_EmpAdminChangePass.setForeground(new java.awt.Color(204, 255, 255));
        btn_EmpAdminChangePass.setText("Change Password");
        btn_EmpAdminChangePass.setBorderColor(new java.awt.Color(153, 0, 153));
        btn_EmpAdminChangePass.setColor(new java.awt.Color(153, 0, 153));
        btn_EmpAdminChangePass.setColorClick(new java.awt.Color(77, 0, 102));
        btn_EmpAdminChangePass.setColorOver(new java.awt.Color(0, 132, 202));
        btn_EmpAdminChangePass.setFocusPainted(false);
        btn_EmpAdminChangePass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_EmpAdminChangePass.setMargin(new java.awt.Insets(2, 2, 3, 14));
        btn_EmpAdminChangePass.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_EmpAdminChangePassMouseMoved(evt);
            }
        });
        btn_EmpAdminChangePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EmpAdminChangePassMouseExited(evt);
            }
        });
        btn_EmpAdminChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmpAdminChangePassActionPerformed(evt);
            }
        });
        sideBar_paint1.add(btn_EmpAdminChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 220, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout (1).png"))); // NOI18N
        sideBar_paint1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 30, 40));

        logoutButton.setBackground(new java.awt.Color(153, 0, 153));
        logoutButton.setBorder(null);
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.setBorderColor(new java.awt.Color(0, 102, 204));
        logoutButton.setColor(new java.awt.Color(153, 0, 153));
        logoutButton.setColorClick(new java.awt.Color(153, 0, 153));
        logoutButton.setColorOver(new java.awt.Color(153, 11, 112));
        logoutButton.setFocusPainted(false);
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutButton.setRadius(25);
        logoutButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                logoutButtonMouseMoved(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        sideBar_paint1.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 140, 40));

        btn_message1.setBackground(new java.awt.Color(77, 0, 102));
        btn_message1.setBorder(null);
        btn_message1.setForeground(new java.awt.Color(204, 255, 255));
        btn_message1.setText("Messages");
        btn_message1.setBorderColor(new java.awt.Color(77, 0, 102));
        btn_message1.setColor(new java.awt.Color(77, 0, 102));
        btn_message1.setColorClick(new java.awt.Color(156, 62, 118));
        btn_message1.setColorOver(new java.awt.Color(0, 153, 204));
        btn_message1.setFocusPainted(false);
        btn_message1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_message1.setMargin(new java.awt.Insets(2, 2, 3, 14));
        btn_message1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_message1MouseMoved(evt);
            }
        });
        btn_message1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_message1ActionPerformed(evt);
            }
        });
        sideBar_paint1.add(btn_message1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/paper-plane.png"))); // NOI18N
        sideBar_paint1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 50, 40));

        Admin_emp_left.add(sideBar_paint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 780));

        mainPanel1.add(Admin_emp_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 880));

        Admin_right_panel1.setBackground(new java.awt.Color(51, 51, 51));
        Admin_right_panel1.setForeground(new java.awt.Color(51, 51, 51));
        Admin_right_panel1.setMinimumSize(new java.awt.Dimension(900, 788));
        Admin_right_panel1.setName(""); // NOI18N
        Admin_right_panel1.setPreferredSize(new java.awt.Dimension(900, 788));
        Admin_right_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admin_Emp_jTabbedPane.setBackground(new java.awt.Color(51, 51, 51));
        Admin_Emp_jTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        Admin_Emp_jTabbedPane.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        Admin_Emp_jTabbedPane.setPreferredSize(new java.awt.Dimension(150, 730));

        panel1.setBackground(new java.awt.Color(0, 51, 51));
        panel1.setForeground(new java.awt.Color(51, 51, 51));
        panel1.setMinimumSize(new java.awt.Dimension(1028, 804));

        admin_Emp_Doctors1.setMinimumSize(new java.awt.Dimension(931, 750));
        admin_Emp_Doctors1.setOpaque(false);
        admin_Emp_Doctors1.setPreferredSize(new java.awt.Dimension(931, 750));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(admin_Emp_Doctors1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(admin_Emp_Doctors1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Admin_Emp_jTabbedPane.addTab("tab6", panel1);

        panel3.setBackground(new java.awt.Color(0, 51, 51));
        panel3.setForeground(new java.awt.Color(51, 51, 51));
        panel3.setMinimumSize(new java.awt.Dimension(1028, 804));
        panel3.setPreferredSize(new java.awt.Dimension(1028, 804));

        admin_Emp_Receptionists1.setOpaque(false);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(admin_Emp_Receptionists1, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(admin_Emp_Receptionists1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        Admin_Emp_jTabbedPane.addTab("tab6", panel3);

        panel4.setBackground(new java.awt.Color(0, 51, 51));
        panel4.setForeground(new java.awt.Color(51, 51, 51));
        panel4.setMinimumSize(new java.awt.Dimension(1028, 804));

        admin_Messages2.setOpaque(false);

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(admin_Messages2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(admin_Messages2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        Admin_Emp_jTabbedPane.addTab("tab6", panel4);

        panel6.setBackground(new java.awt.Color(0, 51, 51));
        panel6.setForeground(new java.awt.Color(51, 51, 51));
        panel6.setMinimumSize(new java.awt.Dimension(1028, 804));

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(admin_Emp_Notification2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(admin_Emp_Notification2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        Admin_Emp_jTabbedPane.addTab("tab6", panel6);

        panel7.setBackground(new java.awt.Color(0, 51, 51));
        panel7.setForeground(new java.awt.Color(51, 51, 51));
        panel7.setMinimumSize(new java.awt.Dimension(1028, 804));

        admin_EmpPassword1.setOpaque(false);

        javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
        panel7.setLayout(panel7Layout);
        panel7Layout.setHorizontalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(admin_EmpPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(521, Short.MAX_VALUE))
        );
        panel7Layout.setVerticalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel7Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(admin_EmpPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        Admin_Emp_jTabbedPane.addTab("tab6", panel7);

        Admin_right_panel1.add(Admin_Emp_jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 1080, 830));

        mainPanel1.add(Admin_right_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1090, 780));

        add(mainPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 780));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EmpAdminDoctorsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpAdminDoctorsMouseMoved
        // TODO add your handling code here:
        btn_EmpAdminDoctors.setRadius(25);
        btn_EmpAdminDoctors.setFocusPainted(false);
        btn_EmpAdminDoctors.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_EmpAdminDoctorsMouseMoved

    private void btn_EmpAdminDoctorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpAdminDoctorsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EmpAdminDoctorsMouseClicked

    private void btn_EmpAdminDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpAdminDoctorsActionPerformed
        // TODO add your handling code here:
         HMS_Demo.sizeFrame(1180, 800);
        Admin_Emp_jTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_btn_EmpAdminDoctorsActionPerformed

    private void btn_EmpAdminReceptionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpAdminReceptionMouseMoved
        // TODO add your handling code here:
        btn_EmpAdminReception.setRadius(25);
        btn_EmpAdminReception.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_EmpAdminReceptionMouseMoved

    private void btn_EmpAdminReceptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpAdminReceptionActionPerformed
        // TODO add your handling code here:
         HMS_Demo.sizeFrame(1180, 800);
         Admin_Emp_jTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_btn_EmpAdminReceptionActionPerformed

    private void btn_EmpAdminMessageMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpAdminMessageMouseMoved
        // TODO add your handling code here:
        btn_EmpAdminMessage.setRadius(25);
        btn_EmpAdminMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_EmpAdminMessageMouseMoved

    private void btn_EmpAdminMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpAdminMessageActionPerformed
        // TODO add your handling code here:
           HMS_Demo.sizeFrame(1180, 800);
          Admin_Emp_jTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_btn_EmpAdminMessageActionPerformed

    private void btn_EmpAdminNotificationMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpAdminNotificationMouseMoved
        // TODO add your handling code here:
        btn_EmpAdminNotification.setRadius(25);
        btn_EmpAdminNotification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_EmpAdminNotificationMouseMoved

    private void btn_EmpAdminNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpAdminNotificationActionPerformed
        // TODO add your handling code here:
          HMS_Demo.sizeFrame(1020, 800);
          Admin_Emp_jTabbedPane.setSelectedIndex(3);
    }//GEN-LAST:event_btn_EmpAdminNotificationActionPerformed

    private void btn_EmpAdminChangePassMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpAdminChangePassMouseMoved
        // TODO add your handling code here:
        btn_EmpAdminChangePass.setRadius(25);
        btn_EmpAdminChangePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_EmpAdminChangePassMouseMoved

    private void btn_EmpAdminChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpAdminChangePassActionPerformed
        // TODO add your handling code here:
          HMS_Demo.sizeFrame(780,800);
          Admin_Emp_jTabbedPane.setSelectedIndex(4);
         
          
    }//GEN-LAST:event_btn_EmpAdminChangePassActionPerformed

    private void logoutButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseMoved
        // TODO add your handling code here:
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutButtonMouseMoved

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    int result=JOptionPane.showConfirmDialog(this, "Are you sure you want to log out from the HMS?","Are you sure you want to log out?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
    if(result==JOptionPane.YES_OPTION){
             HMS_Demo.switchPanel(new LoginPanel());
         } 
       
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void btn_message1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_message1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_message1MouseMoved

    private void btn_message1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_message1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_message1ActionPerformed

    private void btn_EmpAdminDoctorsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpAdminDoctorsMouseExited
        // TODO add your handling code here:
        btn_EmpAdminDoctors.setRadius(0);
    }//GEN-LAST:event_btn_EmpAdminDoctorsMouseExited

    private void btn_EmpAdminReceptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpAdminReceptionMouseExited
        // TODO add your handling code here:
        btn_EmpAdminReception.setRadius(0);
    }//GEN-LAST:event_btn_EmpAdminReceptionMouseExited

    private void btn_EmpAdminMessageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpAdminMessageMouseExited
        // TODO add your handling code here:
        btn_EmpAdminMessage.setRadius(0);
    }//GEN-LAST:event_btn_EmpAdminMessageMouseExited

    private void btn_EmpAdminNotificationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpAdminNotificationMouseExited
        // TODO add your handling code here:
        btn_EmpAdminNotification.setRadius(0);
    }//GEN-LAST:event_btn_EmpAdminNotificationMouseExited

    private void btn_EmpAdminChangePassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpAdminChangePassMouseExited
        // TODO add your handling code here:
        btn_EmpAdminChangePass.setRadius(0);
    }//GEN-LAST:event_btn_EmpAdminChangePassMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Admin_Emp_jTabbedPane;
    private GUI.CustomStyle.Panel Admin_emp_left;
    private GUI.CustomStyle.Panel Admin_right_panel1;
    private GUI.AdminSide.Admin_EmpPassword admin_EmpPassword1;
    private GUI.AdminSide.Admin_Emp_Doctors admin_Emp_Doctors1;
    private GUI.AdminSide.Admin_Emp_Notification admin_Emp_Notification2;
    private GUI.AdminSide.Admin_Emp_Receptionists admin_Emp_Receptionists1;
    private GUI.AdminSide.Admin_Messages admin_Messages2;
    private GUI.CustomStyle.MyButton btn_EmpAdminChangePass;
    private GUI.CustomStyle.MyButton btn_EmpAdminDoctors;
    private GUI.CustomStyle.MyButton btn_EmpAdminMessage;
    private GUI.CustomStyle.MyButton btn_EmpAdminNotification;
    private GUI.CustomStyle.MyButton btn_EmpAdminReception;
    private GUI.CustomStyle.MyButton btn_message1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private GUI.CustomStyle.MyButton logoutButton;
    private GUI.CustomStyle.Panel mainPanel1;
    private GUI.CustomStyle.Panel panel1;
    private GUI.CustomStyle.Panel panel2;
    private GUI.CustomStyle.Panel panel3;
    private GUI.CustomStyle.Panel panel4;
    private GUI.CustomStyle.Panel panel6;
    private GUI.CustomStyle.Panel panel7;
    private GUI.AdminSide.SideBar_paint sideBar_paint1;
    // End of variables declaration//GEN-END:variables
}
