/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.AdminSide;

import GUI.CharacterOnlyFilter;
import GUI.DoubleOnlyFilter;
import GUI.NumberOnlyFilter;
import GUI.PhoneNumberFilter;
import java.awt.Color;
import java.sql.*;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.text.PlainDocument;

/**
 *
 * @author HP
 */
public class Admin_Emp_Doctors extends javax.swing.JPanel {

    private Connection conn;
    private Statement stmt;
    private PreparedStatement pstmt;
    private ResultSet rs;
    /**
     * Creates new form Admin_Emp_Doctors
     */
    public Admin_Emp_Doctors() {
        initComponents();
            JTableHeader tableHeader=doctorsTable.getTableHeader();
        tableHeader.setForeground(new Color(204,255,255));
        tableHeader.setBackground(new Color(82,2,31));
        staffIdTextField.setEditable(false);
        passwordTextField.setText("12345678");
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/HMS_DB";
        String username = "mahnat";
        String password = "mahnat2023";
        conn = DriverManager.getConnection(url, username, password);

        stmt = conn.createStatement();
       
        String createTableQuery="CREATE TABLE if not exists Doctor ("
                    +"  doctorId int auto_increment PRIMARY KEY,"
                    + "speciality VARCHAR(50)," 
                    +" FOREIGN KEY (doctorId) REFERENCES Staff(staffId)" 
                   +");";
        stmt.executeUpdate(createTableQuery);        
        
         fetchFromTable();
        stmt.close();
        conn.close();
        }catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new GUI.CustomStyle.Panel();
        panel1 = new GUI.CustomStyle.Panel();
        searchTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panel6 = new GUI.CustomStyle.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panel8 = new GUI.CustomStyle.Panel();
        panel9 = new GUI.CustomStyle.Panel();
        jLabel3 = new javax.swing.JLabel();
        deleteDoctorButton = new GUI.CustomStyle.MyButton();
        updateDoctorButton = new GUI.CustomStyle.MyButton();
        newDoctorButton = new GUI.CustomStyle.MyButton();
        addDoctorButton = new GUI.CustomStyle.MyButton();
        panel14 = new GUI.CustomStyle.Panel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panel11 = new GUI.CustomStyle.Panel();
        staffIdTextField = new javax.swing.JTextField();
        panel12 = new GUI.CustomStyle.Panel();
        fullNameTextField = new javax.swing.JTextField();
        panel13 = new GUI.CustomStyle.Panel();
        passwordTextField = new javax.swing.JTextField();
        panel18 = new GUI.CustomStyle.Panel();
        ageTextField = new javax.swing.JTextField();
        panel21 = new GUI.CustomStyle.Panel();
        phoneTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panel22 = new GUI.CustomStyle.Panel();
        salaryTextField = new javax.swing.JTextField();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        specialityComboBox = new javax.swing.JComboBox<>();
        panel7 = new GUI.CustomStyle.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorsTable = new javax.swing.JTable();

        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(870, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(190, 247, 255));
        content.setMinimumSize(new java.awt.Dimension(0, 0));
        content.setName(""); // NOI18N
        content.setPreferredSize(new java.awt.Dimension(870, 804));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchTextField.setBorder(null);
        searchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextFieldKeyReleased(evt);
            }
        });
        panel1.add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 600, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 26, 28));

        content.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 660, 40));

        panel6.setBackground(new java.awt.Color(20, 9, 148));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Doctors Data");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doctor (1).png"))); // NOI18N

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.add(panel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 220, 40));

        panel8.setBackground(new java.awt.Color(255, 204, 204));
        panel8.setMinimumSize(new java.awt.Dimension(0, 0));
        panel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel9.setBackground(new java.awt.Color(82, 2, 31));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("USERNAME -->Data");

        javax.swing.GroupLayout panel9Layout = new javax.swing.GroupLayout(panel9);
        panel9.setLayout(panel9Layout);
        panel9Layout.setHorizontalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel9Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panel9Layout.setVerticalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel8.add(panel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));

        deleteDoctorButton.setBackground(new java.awt.Color(23, 169, 232));
        deleteDoctorButton.setBorder(null);
        deleteDoctorButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteDoctorButton.setText("DELETE");
        deleteDoctorButton.setBorderColor(new java.awt.Color(255, 204, 204));
        deleteDoctorButton.setColor(new java.awt.Color(23, 169, 232));
        deleteDoctorButton.setColorClick(new java.awt.Color(23, 133, 232));
        deleteDoctorButton.setColorOver(new java.awt.Color(0, 133, 218));
        deleteDoctorButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteDoctorButton.setRadius(20);
        deleteDoctorButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                deleteDoctorButtonMouseMoved(evt);
            }
        });
        deleteDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDoctorButtonActionPerformed(evt);
            }
        });
        panel8.add(deleteDoctorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 93, 37));

        updateDoctorButton.setBackground(new java.awt.Color(23, 169, 232));
        updateDoctorButton.setBorder(null);
        updateDoctorButton.setForeground(new java.awt.Color(255, 255, 255));
        updateDoctorButton.setText("UPDATE");
        updateDoctorButton.setBorderColor(new java.awt.Color(255, 204, 204));
        updateDoctorButton.setColor(new java.awt.Color(23, 169, 232));
        updateDoctorButton.setColorClick(new java.awt.Color(23, 133, 232));
        updateDoctorButton.setColorOver(new java.awt.Color(0, 133, 218));
        updateDoctorButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateDoctorButton.setRadius(20);
        updateDoctorButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                updateDoctorButtonMouseMoved(evt);
            }
        });
        updateDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDoctorButtonActionPerformed(evt);
            }
        });
        panel8.add(updateDoctorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 98, 37));

        newDoctorButton.setBackground(new java.awt.Color(23, 169, 232));
        newDoctorButton.setBorder(null);
        newDoctorButton.setForeground(new java.awt.Color(255, 255, 255));
        newDoctorButton.setText("NEW");
        newDoctorButton.setBorderColor(new java.awt.Color(255, 204, 204));
        newDoctorButton.setColor(new java.awt.Color(23, 169, 232));
        newDoctorButton.setColorClick(new java.awt.Color(23, 133, 232));
        newDoctorButton.setColorOver(new java.awt.Color(0, 133, 218));
        newDoctorButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newDoctorButton.setRadius(20);
        newDoctorButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                newDoctorButtonMouseMoved(evt);
            }
        });
        newDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDoctorButtonActionPerformed(evt);
            }
        });
        panel8.add(newDoctorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 93, 37));

        addDoctorButton.setBackground(new java.awt.Color(23, 169, 232));
        addDoctorButton.setBorder(null);
        addDoctorButton.setForeground(new java.awt.Color(255, 255, 255));
        addDoctorButton.setText("ADD");
        addDoctorButton.setBorderColor(new java.awt.Color(255, 204, 204));
        addDoctorButton.setColor(new java.awt.Color(23, 169, 232));
        addDoctorButton.setColorClick(new java.awt.Color(23, 133, 232));
        addDoctorButton.setColorOver(new java.awt.Color(0, 133, 218));
        addDoctorButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addDoctorButton.setRadius(20);
        addDoctorButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addDoctorButtonMouseMoved(evt);
            }
        });
        addDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctorButtonActionPerformed(evt);
            }
        });
        panel8.add(addDoctorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 98, 37));

        panel14.setBackground(new java.awt.Color(247, 247, 247));

        javax.swing.GroupLayout panel14Layout = new javax.swing.GroupLayout(panel14);
        panel14.setLayout(panel14Layout);
        panel14Layout.setHorizontalGroup(
            panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        panel14Layout.setVerticalGroup(
            panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel8.add(panel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("FullName");
        panel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("StaffId");
        panel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 60, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setText("Password");
        panel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 60, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 0));
        jLabel7.setText("Speciality");
        panel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 60, 20));

        panel11.setBackground(new java.awt.Color(247, 247, 247));
        panel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staffIdTextField.setBackground(new java.awt.Color(247, 247, 247));
        staffIdTextField.setBorder(null);
        staffIdTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        staffIdTextField.setOpaque(true);
        panel11.add(staffIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));

        panel8.add(panel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 30));

        panel12.setBackground(new java.awt.Color(247, 247, 247));
        panel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullNameTextField.setBackground(new java.awt.Color(247, 247, 247));
        fullNameTextField.setBorder(null);
        fullNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fullNameTextField.setOpaque(true);
        panel12.add(fullNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));
        ((PlainDocument) fullNameTextField.getDocument()).setDocumentFilter(new CharacterOnlyFilter());

        panel8.add(panel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 200, -1));

        panel13.setBackground(new java.awt.Color(247, 247, 247));
        panel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordTextField.setBackground(new java.awt.Color(247, 247, 247));
        passwordTextField.setBorder(null);
        passwordTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordTextField.setOpaque(true);
        panel13.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));

        panel8.add(panel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, -1));

        panel18.setBackground(new java.awt.Color(247, 247, 247));
        panel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ageTextField.setBackground(new java.awt.Color(247, 247, 247));
        ageTextField.setBorder(null);
        ageTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ageTextField.setOpaque(true);
        panel18.add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));
        ((PlainDocument) ageTextField.getDocument()).setDocumentFilter(new NumberOnlyFilter());

        panel8.add(panel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 200, -1));

        panel21.setBackground(new java.awt.Color(247, 247, 247));
        panel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phoneTextField.setBackground(new java.awt.Color(247, 247, 247));
        phoneTextField.setBorder(null);
        phoneTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        phoneTextField.setOpaque(true);
        panel21.add(phoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));
        ((PlainDocument) phoneTextField.getDocument()).setDocumentFilter(new PhoneNumberFilter());

        panel8.add(panel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 200, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 0));
        jLabel10.setText("Age");
        panel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 60, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 0));
        jLabel11.setText("Gender");
        panel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 60, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 0));
        jLabel12.setText("Phone");
        panel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 60, 20));

        panel22.setBackground(new java.awt.Color(247, 247, 247));
        panel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salaryTextField.setBackground(new java.awt.Color(247, 247, 247));
        salaryTextField.setBorder(null);
        salaryTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        salaryTextField.setOpaque(true);
        panel22.add(salaryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));
        ((PlainDocument) salaryTextField.getDocument()).setDocumentFilter(new DoubleOnlyFilter());

        panel8.add(panel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 200, -1));

        maleRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maleRadioButton.setForeground(new java.awt.Color(51, 0, 0));
        maleRadioButton.setText("Male");
        panel8.add(maleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 20));
        sexGroup = new ButtonGroup();
        sexGroup.add(maleRadioButton);
        sexGroup.add(femaleRadioButton);

        femaleRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        femaleRadioButton.setForeground(new java.awt.Color(51, 0, 0));
        femaleRadioButton.setText("Female");
        panel8.add(femaleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 0));
        jLabel13.setText("Salary");
        panel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 60, 20));

        specialityComboBox.setEditable(true);
        specialityComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        specialityComboBox.setForeground(new java.awt.Color(255, 255, 255));
        specialityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General Practitioner","Surgery", "Pediatrics", "Cardiology", "Dentistry" }));
        specialityComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        specialityComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        specialityComboBox.setFocusable(false);
        specialityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialityComboBoxActionPerformed(evt);
            }
        });
        panel8.add(specialityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 160, 30));

        content.add(panel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, 580));

        panel7.setBackground(new java.awt.Color(255, 204, 204));

        doctorsTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        doctorsTable.setForeground(new java.awt.Color(51, 51, 51));
        doctorsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "StaffId", "FullName", "Age", "Gender", "Phone", "Password", "Salary", "Speciality"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doctorsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doctorsTable.setEditingColumn(0);
        doctorsTable.setEditingRow(0);
        doctorsTable.setFocusable(false);
        doctorsTable.setGridColor(new java.awt.Color(204, 204, 255));
        doctorsTable.setOpaque(false);
        doctorsTable.setRowHeight(25);
        doctorsTable.setSelectionBackground(new java.awt.Color(255, 239, 235));
        doctorsTable.setSelectionForeground(new java.awt.Color(0, 51, 255));
        doctorsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(doctorsTable);

        javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
        panel7.setLayout(panel7Layout);
        panel7Layout.setHorizontalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        panel7Layout.setVerticalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel7Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        content.add(panel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 640, 580));

        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 740));
    }// </editor-fold>//GEN-END:initComponents

    private void addDoctorButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDoctorButtonMouseMoved
        // TODO add your handling code here:
        addDoctorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_addDoctorButtonMouseMoved

    private void newDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDoctorButtonActionPerformed
        // TODO add your handling code here:
            staffIdTextField.setText("");
            fullNameTextField.setText("");
            phoneTextField.setText("");
            salaryTextField.setText("");
            passwordTextField.setText("12345678");
            ageTextField.setText("");
            maleRadioButton.setSelected(false);
            femaleRadioButton.setSelected(false);
            specialityComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_newDoctorButtonActionPerformed

    private void newDoctorButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newDoctorButtonMouseMoved
        // TODO add your handling code here:
        newDoctorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_newDoctorButtonMouseMoved

    private void updateDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDoctorButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = doctorsTable.getSelectedRow();
        if (selectedRow >= 0) {
            String id = (String)doctorsTable.getValueAt(selectedRow, 0);
            id=id.substring(1, 5);
             int updatedId=Integer.parseInt(id);
             String name=fullNameTextField.getText();
             String phoneNo=phoneTextField.getText();
             String password=passwordTextField.getText();

             String gender="";
             if(maleRadioButton.isSelected()){
                 gender="Male";
             }else if(femaleRadioButton.isSelected()){
                 gender="Female";
             }
            
             String speciality=(String)specialityComboBox.getSelectedItem();
           if(name.length()==0 || phoneNo.length()==0 ||password.length()==0|| ageTextField.getText().length()==0 ||salaryTextField.getText().length()==0||gender.length()==0||speciality.length()==0){
                JOptionPane.showMessageDialog(this, "Some Data is missing \nplease provide complete information!!.", "Alert", JOptionPane.WARNING_MESSAGE);
            }else {
               try {
                   int age=Integer.parseInt(ageTextField.getText());
                   double salary=Double.parseDouble(salaryTextField.getText());
                   String url = "jdbc:mysql://localhost:3306/HMS_DB";
                   String username = "mahnat";
                   String passwordDB = "mahnat2023";
                   conn = DriverManager.getConnection(url, username, passwordDB);
                   pstmt=conn.prepareStatement("UPDATE Person set name=(?),age=(?),phone=(?),gender=(?),password=(?) where personId=(?) ");
                   pstmt.setString(1, name);
                   pstmt.setInt(2, age);
                   pstmt.setString(3, phoneNo);
                   pstmt.setString(4, gender);
                   pstmt.setString(5, password);
                   pstmt.setInt(6, updatedId);
                   pstmt.executeUpdate();
                   pstmt=conn.prepareStatement("UPDATE Staff set salary=(?) where staffId=(?) ");
                   pstmt.setDouble(1, salary);
                   pstmt.setInt(2, updatedId);
                   pstmt.executeUpdate();
                   pstmt=conn.prepareStatement("UPDATE Doctor set speciality=(?) where doctorId=(?)");
                   pstmt.setString(1, speciality);
                   pstmt.setInt(2, updatedId);
                   pstmt.executeUpdate();
                   rs.close();
                   pstmt.close();
                   conn.close();
               } catch (SQLException e) {
                   System.out.println(e);
               }
                fetchFromTable();
                staffIdTextField.setText("");
                fullNameTextField.setText("");
                phoneTextField.setText("");
                salaryTextField.setText("");
                passwordTextField.setText("12345678");
                ageTextField.setText("");
                maleRadioButton.setSelected(false);
                femaleRadioButton.setSelected(false);
                specialityComboBox.setSelectedIndex(0);
           }
        } else {
            JOptionPane.showMessageDialog(this, "No rows selected please select a row from the table!!.", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_updateDoctorButtonActionPerformed

    private void updateDoctorButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateDoctorButtonMouseMoved
        // TODO add your handling code here:
        updateDoctorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_updateDoctorButtonMouseMoved

    private void deleteDoctorButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteDoctorButtonMouseMoved
        // TODO add your handling code here:
        deleteDoctorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_deleteDoctorButtonMouseMoved

    private void specialityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialityComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialityComboBoxActionPerformed

    private void addDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoctorButtonActionPerformed
        // TODO add your handling code here:
        String name=fullNameTextField.getText();
        String phoneNo=phoneTextField.getText();
        String password=passwordTextField.getText();
        String speciality=(String)specialityComboBox.getSelectedItem();
        String gender="";
        if(maleRadioButton.isSelected()){
            gender="Male";
        }else if(femaleRadioButton.isSelected()){
            gender="Female";
        }
        if(name.length()==0 || phoneNo.length()==0 ||password.length()==0|| ageTextField.getText().length()==0 ||salaryTextField.getText().length()==0||gender.length()==0||speciality.length()==0){
           JOptionPane.showMessageDialog(this, "Some Data is missing \nplease provide complete information!!.", "Alert", JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                int age=Integer.parseInt(ageTextField.getText());
                double salary=Double.parseDouble(salaryTextField.getText());
                String url = "jdbc:mysql://localhost:3306/HMS_DB";
                String username = "mahnat";
                String passwordDB = "mahnat2023";
                conn = DriverManager.getConnection(url, username, passwordDB);
                pstmt=conn.prepareStatement("Insert Into Person (name,age,phone,gender,password) values(?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS);
                pstmt.setString(1, name);
                pstmt.setInt(2, age);
                pstmt.setString(3, phoneNo);
                pstmt.setString(4, gender);
                pstmt.setString(5, password);
                pstmt.executeUpdate();
                rs=pstmt.getGeneratedKeys();
                rs.next();
                int lastInsertedId=rs.getInt(1);
                pstmt=conn.prepareStatement("Insert Into Staff (staffId,salary) values(?,?)");
                pstmt.setInt(1, lastInsertedId);
                pstmt.setDouble(2, salary);
                pstmt.executeUpdate();
                pstmt=conn.prepareStatement("Insert Into Doctor (doctorId,speciality) values(?,?)");
                pstmt.setInt(1, lastInsertedId);
                pstmt.setString(2, speciality);
                pstmt.executeUpdate();
 
                rs.close();
                pstmt.close();
                conn.close();
            } catch (SQLException e) {
                System.out.println(e);
            }
             fetchFromTable();
            staffIdTextField.setText("");
            fullNameTextField.setText("");
            phoneTextField.setText("");
            salaryTextField.setText("");
            passwordTextField.setText("12345678");
            ageTextField.setText("");
            maleRadioButton.setSelected(false);
            femaleRadioButton.setSelected(false);
            specialityComboBox.setSelectedIndex(0);
        }
    }//GEN-LAST:event_addDoctorButtonActionPerformed

    private void doctorsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorsTableMouseClicked
        // TODO add your handling code here:
        int row = doctorsTable.getSelectedRow();
        if(row>=0){
            String id=(String)doctorsTable.getValueAt(row, 0);
            String name=(String)doctorsTable.getValueAt(row, 1);
            String age=String.valueOf(doctorsTable.getValueAt(row, 2));
            String gender=(String)doctorsTable.getValueAt(row, 3);
            String phoneNo=(String)doctorsTable.getValueAt(row, 4);
            String password=(String)doctorsTable.getValueAt(row, 5);
            String salary=String.valueOf(doctorsTable.getValueAt(row, 6));
            String speciality=(String)doctorsTable.getValueAt(row, 7);
            
            staffIdTextField.setText(id);
            fullNameTextField.setText(name);
            ageTextField.setText(String.valueOf(age));
            if(gender.equals("Male")){
                maleRadioButton.setSelected(true);
            }else{
                femaleRadioButton.setSelected(true);
            }
            passwordTextField.setText(password);
            phoneTextField.setText(phoneNo);
            salaryTextField.setText(salary);
            specialityComboBox.setSelectedItem(speciality);
            }
    }//GEN-LAST:event_doctorsTableMouseClicked

    private void searchTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextFieldKeyReleased
        // TODO add your handling code here:
            if (searchTextField.getText().length() != 0) {
                try {
                     String url = "jdbc:mysql://localhost:3306/HMS_DB";
                     String username = "mahnat";
                     String passwordDB = "mahnat2023";
                     conn = DriverManager.getConnection(url, username, passwordDB);
                    String searchText = searchTextField.getText();
                    String idPattern = "D\\d{4}/15";

                    if(searchText.matches(idPattern)){
                        String query = "SELECT D.doctorId,P.name,P.age,P.gender,P.phone,P.password,S.salary,D.speciality FROM Person P join Staff S on P.personId=S.staffID join Doctor D on S.staffId=D.doctorId WHERE D.doctorID LIKE (?);";
                        pstmt=conn.prepareStatement(query);
                        pstmt.setInt(1, Integer.parseInt(searchText.substring(1, 5)));
                        rs = pstmt.executeQuery();
                    }else{
                         String query = "SELECT D.doctorId,P.name,P.age,P.gender,P.phone,P.password,S.salary,D.speciality FROM Person P join Staff S on P.personId=S.staffID join Doctor D on S.staffId=D.doctorId WHERE P.name LIKE (?) or D.doctorID LIKE (?) or P.phone like (?) or P.gender like (?);";
                        pstmt=conn.prepareStatement(query);
                        pstmt.setString(1, searchText+"%");
                        pstmt.setString(2, searchText+"%");
                        pstmt.setString(3, searchText+"%");
                        pstmt.setString(4, searchText+"%");
                        rs = pstmt.executeQuery();
                    }
               DefaultTableModel model = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Make all cells non-editable
                }
            };
            model.addColumn("Id");
            model.addColumn("FullName");
            model.addColumn("Age");
            model.addColumn("Gender");
            model.addColumn("Phone no");
            model.addColumn("Password");
            model.addColumn("Salary");
            model.addColumn("Speciality");

            while (rs.next()) {
                int id=rs.getInt(1);
                String doctorId="";
                if (id < 10) {
                    doctorId += "D000" + id + "/15";
                } else if (id < 100 && id >= 10) {
                    doctorId += "D00" + id + "/15";
                } else if (id < 1000 && id >= 100) {
                    doctorId += "D0" + id + "/15";
                }
                String name=rs.getString(2);
                int age=rs.getInt(3);
                String gender=rs.getString(4);
                String phoneNo=rs.getString(5);
                String password=rs.getString(6);
                double salary=rs.getDouble(7);
                String speciality=rs.getString(8);
                model.addRow(new Object[]{doctorId, name, age, gender,phoneNo,password,salary,speciality});
            }

            doctorsTable.setModel(model);
            rs.close();
            pstmt.close();
            conn.close();
            } catch (SQLException e) {
                System.out.println(e);
            }
        } else {
                fetchFromTable();
        }
    }//GEN-LAST:event_searchTextFieldKeyReleased

    private void deleteDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDoctorButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = doctorsTable.getSelectedRow();
        if (selectedRow >= 0) {
             String id = (String)doctorsTable.getValueAt(selectedRow, 0);
            int result=JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the doctor with id "+id+"?","Are you sure you want to delete the Doctor?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
              id=id.substring(1, 5);
             int deletId=Integer.parseInt(id);
                if(result==JOptionPane.YES_OPTION){
                    try {
                        String url = "jdbc:mysql://localhost:3306/HMS_DB";
                        String username = "mahnat";
                        String passwordDB = "mahnat2023";
                        conn = DriverManager.getConnection(url, username, passwordDB);
                        pstmt=conn.prepareStatement("delete from Doctor where doctorId=?");
                        pstmt.setInt(1, deletId);
                        pstmt.executeUpdate();
                        pstmt=conn.prepareStatement("delete from Staff where staffId=?");
                        pstmt.setInt(1, deletId);
                        pstmt.executeUpdate();
                        pstmt=conn.prepareStatement("delete from Person where personId=?");
                        pstmt.setInt(1, deletId);
                        pstmt.executeUpdate();
                        pstmt.close();
                        conn.close();
                         
                }catch (SQLException e) {
                        System.out.println(e);
                     }
                    fetchFromTable();
                    staffIdTextField.setText("");
                    fullNameTextField.setText("");
                    phoneTextField.setText("");
                    salaryTextField.setText("");
                    passwordTextField.setText("12345678");
                    ageTextField.setText("");
                    maleRadioButton.setSelected(false);
                    femaleRadioButton.setSelected(false);
                    specialityComboBox.setSelectedIndex(0);
            } 
        }else {
            JOptionPane.showMessageDialog(this, "No rows selected please select a row from the table!!.", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteDoctorButtonActionPerformed
     
    public void fetchFromTable() {
        try {
             String url = "jdbc:mysql://localhost:3306/HMS_DB";
             String username = "mahnat";
             String passwordDB = "mahnat2023";
            conn = DriverManager.getConnection(url, username, passwordDB);
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT D.doctorId,P.name,P.age,P.gender,P.phone,P.password,S.salary,D.speciality FROM Person P join Staff S on P.personId=S.staffID join Doctor D on S.staffId=D.doctorId;");

            DefaultTableModel model = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Make all cells non-editable
                }
            };
            model.addColumn("Id");
            model.addColumn("FullName");
            model.addColumn("Age");
            model.addColumn("Gender");
            model.addColumn("Phone no");
            model.addColumn("Password");
            model.addColumn("Salary");
            model.addColumn("Speciality");

        while (rs.next()) {
            int id=rs.getInt(1);
            String adminId="";
            if (id < 10) {
                adminId += "D000" + id + "/15";
            } else if (id < 100 && id >= 10) {
                adminId += "D00" + id + "/15";
            } else if (id < 1000 && id >= 100) {
                adminId += "D0" + id + "/15";
            }
            String name=rs.getString(2);
            int age=rs.getInt(3);
            String gender=rs.getString(4);
            String phoneNo=rs.getString(5);
            String password=rs.getString(6);
            double salary=rs.getDouble(7);
            String speciality=rs.getString(8);
            model.addRow(new Object[]{adminId, name, age, gender,phoneNo,password,salary,speciality});
        }

        doctorsTable.setModel(model);

        rs.close();
        stmt.close();
        conn.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.CustomStyle.MyButton addDoctorButton;
    private javax.swing.JTextField ageTextField;
    private GUI.CustomStyle.Panel content;
    private GUI.CustomStyle.MyButton deleteDoctorButton;
    private javax.swing.JTable doctorsTable;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maleRadioButton;
    private ButtonGroup sexGroup;
    private GUI.CustomStyle.MyButton newDoctorButton;
    private GUI.CustomStyle.Panel panel1;
    private GUI.CustomStyle.Panel panel11;
    private GUI.CustomStyle.Panel panel12;
    private GUI.CustomStyle.Panel panel13;
    private GUI.CustomStyle.Panel panel14;
    private GUI.CustomStyle.Panel panel18;
    private GUI.CustomStyle.Panel panel21;
    private GUI.CustomStyle.Panel panel22;
    private GUI.CustomStyle.Panel panel6;
    private GUI.CustomStyle.Panel panel7;
    private GUI.CustomStyle.Panel panel8;
    private GUI.CustomStyle.Panel panel9;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField salaryTextField;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JComboBox<String> specialityComboBox;
    private javax.swing.JTextField staffIdTextField;
    private GUI.CustomStyle.MyButton updateDoctorButton;
    // End of variables declaration//GEN-END:variables
}
