/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import static GUI.LoginPanel.logedId;
import static GUI.LoginPanel.logedPesonID;
import GUI.OwnerSide.Admin_Owner;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class SignUp extends javax.swing.JPanel {

    private Connection conn;
    private Statement stmt;
    private PreparedStatement pstmt;
    private ResultSet rs;

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new GUI.CustomStyle.Panel();
        sideBar_paint1 = new GUI.AdminSide.SideBar_paint();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panel2 = new GUI.CustomStyle.Panel();
        jLabel1 = new javax.swing.JLabel();
        panel8 = new GUI.CustomStyle.Panel();
        fullnameText = new javax.swing.JTextField();
        panel3 = new GUI.CustomStyle.Panel();
        usernameTextfield = new javax.swing.JTextField();
        panel9 = new GUI.CustomStyle.Panel();
        jPasswordField = new javax.swing.JPasswordField();
        male_rad = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        female_rad = new javax.swing.JRadioButton();
        panel12 = new GUI.CustomStyle.Panel();
        phone_TextField = new javax.swing.JTextField();
        panel11 = new GUI.CustomStyle.Panel();
        AddressTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_login2 = new GUI.CustomStyle.MyButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panel10 = new GUI.CustomStyle.Panel();
        age_spin = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_SignUp = new GUI.CustomStyle.MyButton();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(40, 61, 82));
        setMinimumSize(new java.awt.Dimension(830, 705));
        setPreferredSize(new java.awt.Dimension(830, 705));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(40, 61, 82));
        panel1.setMinimumSize(new java.awt.Dimension(760, 760));
        panel1.setPreferredSize(new java.awt.Dimension(760, 760));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBar_paint1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 188, 229));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("System");
        sideBar_paint1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 110, 50));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hospital (1).png"))); // NOI18N
        sideBar_paint1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 690));

        jLabel13.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 188, 229));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Hospital Management");
        sideBar_paint1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 110, 50));

        jLabel14.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 188, 229));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("System");
        sideBar_paint1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 110, 50));

        panel1.add(sideBar_paint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 700));

        panel2.setBackground(new java.awt.Color(40, 61, 82));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/patients.png"))); // NOI18N
        panel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 140, 130));

        panel8.setBackground(new java.awt.Color(0, 153, 153));

        fullnameText.setBackground(new java.awt.Color(0, 153, 153));
        fullnameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fullnameText.setForeground(new java.awt.Color(204, 255, 255));
        fullnameText.setBorder(null);
        fullnameText.setCaretColor(new java.awt.Color(0, 239, 253));

        javax.swing.GroupLayout panel8Layout = new javax.swing.GroupLayout(panel8);
        panel8.setLayout(panel8Layout);
        panel8Layout.setHorizontalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(fullnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel8Layout.setVerticalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullnameText, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panel2.add(panel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 250, 40));

        panel3.setBackground(new java.awt.Color(0, 153, 153));
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTextfield.setBackground(new java.awt.Color(0, 153, 153));
        usernameTextfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameTextfield.setForeground(new java.awt.Color(204, 255, 255));
        usernameTextfield.setBorder(null);
        usernameTextfield.setCaretColor(new java.awt.Color(0, 239, 253));
        panel3.add(usernameTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        panel2.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 250, 40));

        panel9.setBackground(new java.awt.Color(0, 153, 153));

        jPasswordField.setBackground(new java.awt.Color(0, 153, 153));
        jPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(204, 255, 255));
        jPasswordField.setBorder(null);
        jPasswordField.setCaretColor(new java.awt.Color(0, 239, 253));
        jPasswordField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel9Layout = new javax.swing.GroupLayout(panel9);
        panel9.setLayout(panel9Layout);
        panel9Layout.setHorizontalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel9Layout.setVerticalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel2.add(panel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        male_rad.setBackground(new java.awt.Color(40, 61, 82));
        male_rad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        male_rad.setForeground(new java.awt.Color(204, 204, 204));
        male_rad.setText("Male");
        male_rad.setBorder(null);
        male_rad.setFocusPainted(false);
        male_rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_radActionPerformed(evt);
            }
        });
        panel2.add(male_rad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Gender");
        panel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 70, 30));

        female_rad.setBackground(new java.awt.Color(40, 61, 82));
        female_rad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        female_rad.setForeground(new java.awt.Color(204, 204, 204));
        female_rad.setText("Female");
        female_rad.setBorder(null);
        female_rad.setFocusPainted(false);
        panel2.add(female_rad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        panel12.setBackground(new java.awt.Color(0, 153, 153));

        phone_TextField.setBackground(new java.awt.Color(0, 153, 153));
        phone_TextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phone_TextField.setForeground(new java.awt.Color(204, 255, 255));
        phone_TextField.setBorder(null);
        phone_TextField.setCaretColor(new java.awt.Color(0, 239, 253));

        javax.swing.GroupLayout panel12Layout = new javax.swing.GroupLayout(panel12);
        panel12.setLayout(panel12Layout);
        panel12Layout.setHorizontalGroup(
            panel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(phone_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel12Layout.setVerticalGroup(
            panel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(phone_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panel2.add(panel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        panel11.setBackground(new java.awt.Color(0, 153, 153));

        AddressTextField.setBackground(new java.awt.Color(0, 153, 153));
        AddressTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AddressTextField.setForeground(new java.awt.Color(204, 255, 255));
        AddressTextField.setBorder(null);
        AddressTextField.setCaretColor(new java.awt.Color(0, 239, 253));
        AddressTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panel11Layout = new javax.swing.GroupLayout(panel11);
        panel11.setLayout(panel11Layout);
        panel11Layout.setHorizontalGroup(
            panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel11Layout.setVerticalGroup(
            panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panel2.add(panel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SignUp");
        panel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 500, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Already have account ? |");
        panel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, -1, 30));

        btn_login2.setBorder(null);
        btn_login2.setForeground(new java.awt.Color(0, 239, 253));
        btn_login2.setText("SignIn");
        btn_login2.setBorderColor(new java.awt.Color(40, 61, 82));
        btn_login2.setColor(new java.awt.Color(40, 61, 82));
        btn_login2.setColorClick(new java.awt.Color(40, 61, 82));
        btn_login2.setColorOver(new java.awt.Color(40, 61, 82));
        btn_login2.setFocusPainted(false);
        btn_login2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_login2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_login2MouseMoved(evt);
            }
        });
        btn_login2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_login2MouseExited(evt);
            }
        });
        btn_login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login2ActionPerformed(evt);
            }
        });
        panel2.add(btn_login2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 120, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Address");
        panel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Phone");
        panel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 50, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Age");
        panel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, 40));

        panel10.setBackground(new java.awt.Color(0, 153, 153));

        age_spin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        age_spin.setModel(new javax.swing.SpinnerNumberModel(1, 1, 115, 1));
        age_spin.setBorder(null);
        age_spin.setOpaque(true);

        javax.swing.GroupLayout panel10Layout = new javax.swing.GroupLayout(panel10);
        panel10.setLayout(panel10Layout);
        panel10Layout.setHorizontalGroup(
            panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(age_spin, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel10Layout.setVerticalGroup(
            panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(age_spin, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panel2.add(panel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 100, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Password");
        panel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, 40));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Username");
        panel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 80, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("FullName");
        panel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 80, 40));

        btn_SignUp.setBackground(new java.awt.Color(153, 0, 153));
        btn_SignUp.setBorder(null);
        btn_SignUp.setForeground(new java.awt.Color(204, 255, 255));
        btn_SignUp.setText("Register");
        btn_SignUp.setAutoscrolls(true);
        btn_SignUp.setBorderColor(new java.awt.Color(153, 0, 153));
        btn_SignUp.setColor(new java.awt.Color(153, 0, 153));
        btn_SignUp.setColorClick(new java.awt.Color(153, 0, 102));
        btn_SignUp.setColorOver(new java.awt.Color(102, 0, 102));
        btn_SignUp.setFocusPainted(false);
        btn_SignUp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_SignUp.setRadius(50);
        btn_SignUp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_SignUpMouseMoved(evt);
            }
        });
        btn_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignUpActionPerformed(evt);
            }
        });
        panel2.add(btn_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 140, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/medical-team (2).png"))); // NOI18N
        panel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 81, -1));

        panel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 530, 690));

        add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_login2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_login2MouseMoved
        // TODO add your handling code here:
        btn_login2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login2.setForeground(new java.awt.Color(255, 153, 102));
    }//GEN-LAST:event_btn_login2MouseMoved

    private void btn_login2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_login2MouseExited
        // TODO add your handling code here:
        btn_login2.setForeground(new java.awt.Color(0, 239, 253));
    }//GEN-LAST:event_btn_login2MouseExited

    private void btn_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignUpActionPerformed
         String name=fullnameText.getText();
        String phoneNo=phone_TextField.getText();
        String password=jPasswordField.getText();
        String address=AddressTextField.getText();
        String gender="";
        if(male_rad.isSelected()){
            gender="Male";
            
        }else if(female_rad.isSelected()){
            gender="Female";
        }
        if(name.length()==0 || phoneNo.length()==0 ||password.length()==0 ||gender.length()==0){
           JOptionPane.showMessageDialog(this, "Some Data is missing \nplease provide complete information!!.", "Alert", JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                int age=(int) age_spin.getValue();
                String url = "jdbc:mysql://localhost:3306/HMS_DB";
                String username = "mahnat";
                String passwordDB = "mahnat2023";
                conn = DriverManager.getConnection(url, username, passwordDB);
                pstmt=conn.prepareStatement("Insert Into Person (name,age,phone,gender,password) values(?,?,?,?,?)");
                pstmt.setString(1, name);
                pstmt.setInt(2, age);
                pstmt.setString(3, phoneNo);
                pstmt.setString(4, gender);
                pstmt.setString(5, password);
                pstmt.executeUpdate();
                rs=pstmt.getGeneratedKeys();
                rs.next();
                int lastInsertedId=rs.getInt(1);
                pstmt=conn.prepareStatement("Insert Into Patient (patientId,checkInStatus,address,bill,checkInValue) values(?,?,?,?,?)");
                pstmt.setInt(1, lastInsertedId);
                pstmt.setBoolean(2, true);
                pstmt.setString(3, address);
                pstmt.setDouble(4, 200);
                pstmt.setString(5, "Checked-In");
                pstmt.executeUpdate();
                
 
                rs.close();
                pstmt.close();
                conn.close();
        JOptionPane.showMessageDialog(this, "Your Record is Added successfully.", "Congratulation", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                System.out.println(e);
            }
   
     }
        
    }//GEN-LAST:event_btn_SignUpActionPerformed

    private void btn_SignUpMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SignUpMouseMoved
        // TODO add your handling code here:
        btn_SignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_SignUpMouseMoved

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void male_radActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_radActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_male_radActionPerformed

    private void btn_login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login2ActionPerformed
        // TODO add your handling code here:
        HMS_Demo.switchPanel(new LoginPanel());
    }//GEN-LAST:event_btn_login2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JSpinner age_spin;
    private GUI.CustomStyle.MyButton btn_SignUp;
    private GUI.CustomStyle.MyButton btn_login2;
    private javax.swing.JRadioButton female_rad;
    private javax.swing.JTextField fullnameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JRadioButton male_rad;
    private GUI.CustomStyle.Panel panel1;
    private GUI.CustomStyle.Panel panel10;
    private GUI.CustomStyle.Panel panel11;
    private GUI.CustomStyle.Panel panel12;
    private GUI.CustomStyle.Panel panel2;
    private GUI.CustomStyle.Panel panel3;
    private GUI.CustomStyle.Panel panel8;
    private GUI.CustomStyle.Panel panel9;
    private javax.swing.JTextField phone_TextField;
    private GUI.AdminSide.SideBar_paint sideBar_paint1;
    private javax.swing.JTextField usernameTextfield;
    // End of variables declaration//GEN-END:variables
}
