/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.PatientSide;

import GUI.LoginPanel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Patient_Password extends javax.swing.JPanel {
private Connection conn;
    private PreparedStatement pstmt;
    
    public Patient_Password() {
        initComponents();
        userNameField.setText(LoginPanel.logedPesonID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new GUI.CustomStyle.Panel();
        panel9 = new GUI.CustomStyle.Panel();
        jLabel3 = new javax.swing.JLabel();
        panel6 = new GUI.CustomStyle.Panel();
        jLabel1 = new javax.swing.JLabel();
        panel8 = new GUI.CustomStyle.Panel();
        btn_save = new GUI.CustomStyle.MyButton();
        panel14 = new GUI.CustomStyle.Panel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panel12 = new GUI.CustomStyle.Panel();
        userNameField = new javax.swing.JTextField();
        panel15 = new GUI.CustomStyle.Panel();
        confirmedPasswordTextField = new javax.swing.JTextField();
        panel13 = new GUI.CustomStyle.Panel();
        passwordTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));

        content.setBackground(new java.awt.Color(190, 247, 255));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel9.setBackground(new java.awt.Color(82, 2, 31));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Account Configuration");

        javax.swing.GroupLayout panel9Layout = new javax.swing.GroupLayout(panel9);
        panel9.setLayout(panel9Layout);
        panel9Layout.setHorizontalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel9Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel9Layout.setVerticalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        content.add(panel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 220, -1));

        panel6.setBackground(new java.awt.Color(20, 9, 148));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient");

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        content.add(panel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 160, 40));

        panel8.setBackground(new java.awt.Color(255, 204, 204));
        panel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_save.setBackground(new java.awt.Color(23, 169, 232));
        btn_save.setBorder(null);
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setText("SAVE");
        btn_save.setBorderColor(new java.awt.Color(255, 204, 204));
        btn_save.setColor(new java.awt.Color(23, 169, 232));
        btn_save.setColorClick(new java.awt.Color(23, 133, 232));
        btn_save.setColorOver(new java.awt.Color(0, 133, 218));
        btn_save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_save.setRadius(20);
        btn_save.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_saveMouseMoved(evt);
            }
        });
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        panel8.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 140, 50));

        panel14.setBackground(new java.awt.Color(247, 247, 247));

        javax.swing.GroupLayout panel14Layout = new javax.swing.GroupLayout(panel14);
        panel14.setLayout(panel14Layout);
        panel14Layout.setHorizontalGroup(
            panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel14Layout.setVerticalGroup(
            panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel8.add(panel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("Username");
        panel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 80, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setText("Confirm");
        panel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, 20));

        panel12.setBackground(new java.awt.Color(247, 247, 247));
        panel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameField.setEditable(false);
        userNameField.setBackground(new java.awt.Color(247, 247, 247));
        userNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userNameField.setForeground(new java.awt.Color(51, 51, 51));
        userNameField.setBorder(null);
        userNameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userNameField.setOpaque(true);
        userNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameFieldFocusLost(evt);
            }
        });
        panel12.add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 40));

        panel8.add(panel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 340, 40));

        panel15.setBackground(new java.awt.Color(247, 247, 247));
        panel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmedPasswordTextField.setBackground(new java.awt.Color(247, 247, 247));
        confirmedPasswordTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmedPasswordTextField.setForeground(new java.awt.Color(51, 51, 51));
        confirmedPasswordTextField.setToolTipText("");
        confirmedPasswordTextField.setBorder(null);
        confirmedPasswordTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        confirmedPasswordTextField.setOpaque(true);
        confirmedPasswordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmedPasswordTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmedPasswordTextFieldFocusLost(evt);
            }
        });
        confirmedPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmedPasswordTextFieldActionPerformed(evt);
            }
        });
        panel15.add(confirmedPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 40));

        panel8.add(panel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 340, 40));

        panel13.setBackground(new java.awt.Color(247, 247, 247));
        panel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordTextField.setBackground(new java.awt.Color(247, 247, 247));
        passwordTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordTextField.setForeground(new java.awt.Color(51, 51, 51));
        passwordTextField.setToolTipText("");
        passwordTextField.setBorder(null);
        passwordTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordTextField.setOpaque(true);
        passwordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTextFieldFocusLost(evt);
            }
        });
        panel13.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 40));

        panel8.add(panel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 340, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 0));
        jLabel10.setText("Password");
        panel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, 20));

        content.add(panel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 420, 420));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profile.png"))); // NOI18N
        content.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 170, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseMoved
        // TODO add your handling code here:
        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_saveMouseMoved

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        String passwordProvided=passwordTextField.getText();
        String confirmedPassword=confirmedPasswordTextField.getText();
        if(passwordProvided.length()==0 || confirmedPassword.length()==0){
             JOptionPane.showMessageDialog(this, "You have two provide both passwords!!.", "Alert", JOptionPane.WARNING_MESSAGE);
        }else{
            if(passwordProvided.equals(confirmedPassword)){
                try {
                     String url = "jdbc:mysql://localhost:3306/HMS_DB";
                     String username1 = "mahnat";
                     String password1 = "mahnat2023";
                     conn = DriverManager.getConnection(url, username1, password1);
                     pstmt=conn.prepareStatement("update Person set password=(?) where personId =(?);");
                     pstmt.setString(1, passwordProvided);
                     pstmt.setInt(2, LoginPanel.logedId);
                     int rows=pstmt.executeUpdate();
                     if(rows>0){
                         passwordTextField.setText("");
                         confirmedPasswordTextField.setText("");
                         JOptionPane.showMessageDialog(this, "You have successfully changed your password!!.", "Successfully Changed Password", JOptionPane.PLAIN_MESSAGE);
                     }
                } catch (SQLException e) {
                    System.out.println(e);
                }           
            }else{
               JOptionPane.showMessageDialog(this, "You passwords don't match!!.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void userNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFieldFocusGained
        // TODO add your handling code here:
        //username_placeholder.setText("");
    }//GEN-LAST:event_userNameFieldFocusGained

    private void userNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFieldFocusLost
        // TODO add your handling code here:
        //username_placeholder.setForeground(new java.awt.Color(187,187,187));
        //username_placeholder.setFont(new java.awt.Font("Segoe UI", 0, 14));
        //username_placeholder.setText("username");
    }//GEN-LAST:event_userNameFieldFocusLost

    private void passwordTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextFieldFocusGained
        // TODO add your handling code here:
        //owner_Admin_password.setText("");
    }//GEN-LAST:event_passwordTextFieldFocusGained

    private void passwordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextFieldFocusLost
        // TODO add your handling code here:
//        owner_Admin_password.setForeground(new java.awt.Color(187,187,187));
//        owner_Admin_password.setFont(new java.awt.Font("Segoe UI", 0, 14));
//        owner_Admin_password.setText("password");
    }//GEN-LAST:event_passwordTextFieldFocusLost

    private void confirmedPasswordTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmedPasswordTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmedPasswordTextFieldFocusGained

    private void confirmedPasswordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmedPasswordTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmedPasswordTextFieldFocusLost

    private void confirmedPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmedPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmedPasswordTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.CustomStyle.MyButton btn_save;
    private javax.swing.JTextField confirmedPasswordTextField;
    private GUI.CustomStyle.Panel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private GUI.CustomStyle.Panel panel12;
    private GUI.CustomStyle.Panel panel13;
    private GUI.CustomStyle.Panel panel14;
    private GUI.CustomStyle.Panel panel15;
    private GUI.CustomStyle.Panel panel6;
    private GUI.CustomStyle.Panel panel8;
    private GUI.CustomStyle.Panel panel9;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
