/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.OwnerSide;
import GUI.DoubleOnlyFilter;
import GUI.CharacterOnlyFilter;
import GUI.NumberOnlyFilter;
import GUI.PhoneNumberFilter;
import java.awt.Color;
import java.sql.*;
import javax.swing.text.PlainDocument;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author HP
 */
public class Admin_Owner_Employeed extends javax.swing.JPanel {

    private Connection conn;
    private Statement stmt;
    private PreparedStatement pstmt;
    private ResultSet rs;
    /**
     * Creates new form AdminEmployeed
     */
    public Admin_Owner_Employeed() {
        initComponents();
        JTableHeader tableHeader=adminsTable.getTableHeader();
        tableHeader.setForeground(new Color(204,255,255));
        tableHeader.setBackground(new Color(82,2,31));
        
        
        idTextField.setEditable(false);
        passwordTextField.setText("12345678");
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/HMS_DB";
        String username = "mahnat";
        String password = "mahnat2023";
        conn = DriverManager.getConnection(url, username, password);

        stmt = conn.createStatement();
        String createTableQuery= "CREATE TABLE if not exists Staff (" +
                                "  staffId int auto_increment KEY," +
                                "  salary DOUBLE," +
                                "  FOREIGN KEY (staffId) REFERENCES Person(personId)" +
                                ");";
        stmt.executeUpdate(createTableQuery);
        createTableQuery="CREATE TABLE if not exists Admin ("
                    +"  staffId INT auto_increment PRIMARY KEY," 
                    +"  FOREIGN KEY (staffId) REFERENCES Staff(staffId)" 
                   +");";
        stmt.executeUpdate(createTableQuery);        
        
         fetchFromTable();
        stmt.close();
        conn.close();
        }catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new GUI.CustomStyle.Panel();
        panel1 = new GUI.CustomStyle.Panel();
        searchTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panel6 = new GUI.CustomStyle.Panel();
        jLabel1 = new javax.swing.JLabel();
        panel7 = new GUI.CustomStyle.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminsTable = new javax.swing.JTable();
        panel8 = new GUI.CustomStyle.Panel();
        panel9 = new GUI.CustomStyle.Panel();
        jLabel3 = new javax.swing.JLabel();
        deleteButton = new GUI.CustomStyle.MyButton();
        updateButton = new GUI.CustomStyle.MyButton();
        newButton = new GUI.CustomStyle.MyButton();
        addButton = new GUI.CustomStyle.MyButton();
        panel14 = new GUI.CustomStyle.Panel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panel11 = new GUI.CustomStyle.Panel();
        idTextField = new javax.swing.JTextField();
        panel12 = new GUI.CustomStyle.Panel();
        phoneNoTextField = new javax.swing.JTextField();
        panel13 = new GUI.CustomStyle.Panel();
        passwordTextField = new javax.swing.JTextField();
        panel18 = new GUI.CustomStyle.Panel();
        salaryTextField = new javax.swing.JTextField();
        panel15 = new GUI.CustomStyle.Panel();
        fullNameTextField = new javax.swing.JTextField();
        maleRadiButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        panel21 = new GUI.CustomStyle.Panel();
        jLabel9 = new javax.swing.JLabel();
        panel19 = new GUI.CustomStyle.Panel();
        ageTextField = new javax.swing.JTextField();
        panel16 = new GUI.CustomStyle.Panel();
        fullname_placeholder2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        content.setBackground(new java.awt.Color(190, 247, 255));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchTextField.setBorder(null);
        searchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextFieldKeyReleased(evt);
            }
        });
        panel1.add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 600, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 26, 28));

        content.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 660, 40));

        panel6.setBackground(new java.awt.Color(20, 9, 148));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Employeed Admins Data");

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        content.add(panel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 260, 40));

        panel7.setBackground(new java.awt.Color(255, 204, 204));

        adminsTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminsTable.setForeground(new java.awt.Color(51, 51, 51));
        adminsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "FullName", "Age", "Gender", "Phone no", "Password", "Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        adminsTable.setCursor(null);
        adminsTable.setEditingColumn(0);
        adminsTable.setEditingRow(0);
        adminsTable.setFocusable(false);
        adminsTable.setGridColor(new java.awt.Color(204, 204, 255));
        adminsTable.setOpaque(false);
        adminsTable.setRowHeight(25);
        adminsTable.setSelectionBackground(new java.awt.Color(255, 239, 235));
        adminsTable.setSelectionForeground(new java.awt.Color(0, 51, 255));
        adminsTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        adminsTable.setShowGrid(true);
        adminsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminsTableMouseClicked(evt);
            }
        });
        adminsTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adminsTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(adminsTable);

        javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
        panel7.setLayout(panel7Layout);
        panel7Layout.setHorizontalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel7Layout.setVerticalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        content.add(panel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 590, 500));

        panel8.setBackground(new java.awt.Color(255, 204, 204));
        panel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel9.setBackground(new java.awt.Color(82, 2, 31));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("USERNAME -->Data");

        javax.swing.GroupLayout panel9Layout = new javax.swing.GroupLayout(panel9);
        panel9.setLayout(panel9Layout);
        panel9Layout.setHorizontalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel9Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel9Layout.setVerticalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel8.add(panel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));

        deleteButton.setBackground(new java.awt.Color(23, 169, 232));
        deleteButton.setBorder(null);
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("DELETE");
        deleteButton.setBorderColor(new java.awt.Color(255, 204, 204));
        deleteButton.setColor(new java.awt.Color(23, 169, 232));
        deleteButton.setColorClick(new java.awt.Color(23, 133, 232));
        deleteButton.setColorOver(new java.awt.Color(0, 133, 218));
        deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteButton.setRadius(20);
        deleteButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                deleteButtonMouseMoved(evt);
            }
        });
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        panel8.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 93, 37));

        updateButton.setBackground(new java.awt.Color(23, 169, 232));
        updateButton.setBorder(null);
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("UPDATE");
        updateButton.setBorderColor(new java.awt.Color(255, 204, 204));
        updateButton.setColor(new java.awt.Color(23, 169, 232));
        updateButton.setColorClick(new java.awt.Color(23, 133, 232));
        updateButton.setColorOver(new java.awt.Color(0, 133, 218));
        updateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateButton.setRadius(20);
        updateButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                updateButtonMouseMoved(evt);
            }
        });
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        panel8.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 98, 37));

        newButton.setBackground(new java.awt.Color(23, 169, 232));
        newButton.setBorder(null);
        newButton.setForeground(new java.awt.Color(255, 255, 255));
        newButton.setText("NEW");
        newButton.setBorderColor(new java.awt.Color(255, 204, 204));
        newButton.setColor(new java.awt.Color(23, 169, 232));
        newButton.setColorClick(new java.awt.Color(23, 133, 232));
        newButton.setColorOver(new java.awt.Color(0, 133, 218));
        newButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newButton.setRadius(20);
        newButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                newButtonMouseMoved(evt);
            }
        });
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });
        panel8.add(newButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 93, 37));

        addButton.setBackground(new java.awt.Color(23, 169, 232));
        addButton.setBorder(null);
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD");
        addButton.setBorderColor(new java.awt.Color(255, 204, 204));
        addButton.setColor(new java.awt.Color(23, 169, 232));
        addButton.setColorClick(new java.awt.Color(23, 133, 232));
        addButton.setColorOver(new java.awt.Color(0, 133, 218));
        addButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addButton.setRadius(20);
        addButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addButtonMouseMoved(evt);
            }
        });
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        panel8.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 98, 37));

        panel14.setBackground(new java.awt.Color(247, 247, 247));

        javax.swing.GroupLayout panel14Layout = new javax.swing.GroupLayout(panel14);
        panel14.setLayout(panel14Layout);
        panel14Layout.setHorizontalGroup(
            panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel14Layout.setVerticalGroup(
            panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel8.add(panel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("ID");
        panel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 60, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("Phone no");
        panel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setText("Password");
        panel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 60, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 0));
        jLabel7.setText("Salary");
        panel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 60, 30));

        panel11.setBackground(new java.awt.Color(247, 247, 247));
        panel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idTextField.setBackground(new java.awt.Color(247, 247, 247));
        idTextField.setBorder(null);
        idTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        idTextField.setOpaque(true);
        panel11.add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 0, 90, 30));

        panel8.add(panel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 120, 30));

        panel12.setBackground(new java.awt.Color(247, 247, 247));
        panel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phoneNoTextField.setBackground(new java.awt.Color(247, 247, 247));
        phoneNoTextField.setBorder(null);
        phoneNoTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        phoneNoTextField.setOpaque(true);
        panel12.add(phoneNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));
        ((PlainDocument) phoneNoTextField.getDocument()).setDocumentFilter(new PhoneNumberFilter());

        panel8.add(panel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 200, -1));

        panel13.setBackground(new java.awt.Color(247, 247, 247));
        panel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordTextField.setBackground(new java.awt.Color(247, 247, 247));
        passwordTextField.setBorder(null);
        passwordTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordTextField.setOpaque(true);
        panel13.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));

        panel8.add(panel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 200, -1));

        panel18.setBackground(new java.awt.Color(247, 247, 247));
        panel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salaryTextField.setBackground(new java.awt.Color(247, 247, 247));
        salaryTextField.setBorder(null);
        salaryTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        salaryTextField.setOpaque(true);
        panel18.add(salaryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));
        ((PlainDocument) salaryTextField.getDocument()).setDocumentFilter(new DoubleOnlyFilter());

        panel8.add(panel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 200, -1));

        panel15.setBackground(new java.awt.Color(247, 247, 247));
        panel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullNameTextField.setBackground(new java.awt.Color(247, 247, 247));
        fullNameTextField.setBorder(null);
        fullNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fullNameTextField.setOpaque(true);
        panel15.add(fullNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));
        ((PlainDocument) fullNameTextField.getDocument()).setDocumentFilter(new CharacterOnlyFilter());

        panel8.add(panel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 30));

        maleRadiButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maleRadiButton.setForeground(new java.awt.Color(51, 0, 0));
        maleRadiButton.setText("Male");
        panel8.add(maleRadiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, 20));
        sexGroup = new ButtonGroup();
        sexGroup.add(maleRadiButton);
        sexGroup.add(femaleRadioButton);

        femaleRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        femaleRadioButton.setForeground(new java.awt.Color(51, 0, 0));
        femaleRadioButton.setText("Female");
        panel8.add(femaleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 0));
        jLabel11.setText("Gender");
        panel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 60, 30));

        panel21.setBackground(new java.awt.Color(247, 247, 247));
        panel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel8.add(panel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 200, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 0));
        jLabel9.setText("Age");
        panel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 60, 40));

        panel19.setBackground(new java.awt.Color(247, 247, 247));
        panel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ageTextField.setBackground(new java.awt.Color(247, 247, 247));
        ageTextField.setBorder(null);
        ageTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ageTextField.setOpaque(true);
        panel19.add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));
        ((PlainDocument) ageTextField.getDocument()).setDocumentFilter(new NumberOnlyFilter());

        panel8.add(panel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 200, -1));

        panel16.setBackground(new java.awt.Color(247, 247, 247));
        panel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullname_placeholder2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        fullname_placeholder2.setText(" fullname");
        panel16.add(fullname_placeholder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        panel8.add(panel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 0));
        jLabel8.setText("FullName");
        panel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 20));

        content.add(panel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 240, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseMoved
        // TODO add your handling code here:
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_deleteButtonMouseMoved

    private void updateButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseMoved
        // TODO add your handling code here:
        updateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_updateButtonMouseMoved

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = adminsTable.getSelectedRow();
        if (selectedRow >= 0) {
            String id = (String)adminsTable.getValueAt(selectedRow, 0);
            id=id.substring(1, 5);
             int updatedId=Integer.parseInt(id);
             String name=fullNameTextField.getText();
             String phoneNo=phoneNoTextField.getText();
             String password=passwordTextField.getText();

             String gender="";
             if(maleRadiButton.isSelected()){
                 gender="Male";
             }else if(femaleRadioButton.isSelected()){
                 gender="Female";
             }
            

           if(name.length()==0 || phoneNo.length()==0 ||password.length()==0|| ageTextField.getText().length()==0 ||salaryTextField.getText().length()==0||gender.length()==0){
                JOptionPane.showMessageDialog(this, "Some Data is missing \nplease provide complete information!!.", "Alert", JOptionPane.WARNING_MESSAGE);
            }else {
               try {
                   int age=Integer.parseInt(ageTextField.getText());
                   double salary=Double.parseDouble(salaryTextField.getText());
                   String url = "jdbc:mysql://localhost:3306/HMS_DB";
                   String username = "mahnat";
                   String passwordDB = "mahnat2023";
                   conn = DriverManager.getConnection(url, username, passwordDB);
                   pstmt=conn.prepareStatement("UPDATE Person set name=(?),age=(?),phone=(?),gender=(?),password=(?) where personId=(?) ");
                   pstmt.setString(1, name);
                   pstmt.setInt(2, age);
                   pstmt.setString(3, phoneNo);
                   pstmt.setString(4, gender);
                   pstmt.setString(5, password);
                   pstmt.setInt(6, updatedId);
                   pstmt.executeUpdate();
                   pstmt=conn.prepareStatement("UPDATE Staff set salary=(?) where staffId=(?) ");
                   pstmt.setDouble(1, salary);
                   pstmt.setInt(2, updatedId);
                   pstmt.executeUpdate();
                   rs.close();
                   pstmt.close();
                   conn.close();
               } catch (SQLException e) {
                   System.out.println(e);
               }
                fetchFromTable();
                idTextField.setText("");
                fullNameTextField.setText("");
                phoneNoTextField.setText("");
                salaryTextField.setText("");
                passwordTextField.setText("12345678");
                ageTextField.setText("");
                maleRadiButton.setSelected(false);
                femaleRadioButton.setSelected(false);
           }
        } else {
            JOptionPane.showMessageDialog(this, "No rows selected please select a row from the table!!.", "Alert", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_updateButtonActionPerformed

    private void newButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newButtonMouseMoved
        // TODO add your handling code here:
        newButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_newButtonMouseMoved

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        // TODO add your handling code here:
            idTextField.setText("");
            fullNameTextField.setText("");
            phoneNoTextField.setText("");
            salaryTextField.setText("");
            passwordTextField.setText("12345678");
            ageTextField.setText("");
            maleRadiButton.setSelected(false);
            femaleRadioButton.setSelected(false);
    }//GEN-LAST:event_newButtonActionPerformed

    private void addButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseMoved
        // TODO add your handling code here:
        addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_addButtonMouseMoved

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String name=fullNameTextField.getText();
        String phoneNo=phoneNoTextField.getText();
        String password=passwordTextField.getText();
        
        String gender="";
        if(maleRadiButton.isSelected()){
            gender="Male";
        }else if(femaleRadioButton.isSelected()){
            gender="Female";
        }
        if(name.length()==0 || phoneNo.length()==0 ||password.length()==0|| ageTextField.getText().length()==0 ||salaryTextField.getText().length()==0||gender.length()==0){
           JOptionPane.showMessageDialog(this, "Some Data is missing \nplease provide complete information!!.", "Alert", JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                int age=Integer.parseInt(ageTextField.getText());
                double salary=Double.parseDouble(salaryTextField.getText());
                String url = "jdbc:mysql://localhost:3306/HMS_DB";
                String username = "mahnat";
                String passwordDB = "mahnat2023";
                conn = DriverManager.getConnection(url, username, passwordDB);
                pstmt=conn.prepareStatement("Insert Into Person (name,age,phone,gender,password) values(?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS);
                pstmt.setString(1, name);
                pstmt.setInt(2, age);
                pstmt.setString(3, phoneNo);
                pstmt.setString(4, gender);
                pstmt.setString(5, password);
                pstmt.executeUpdate();
                rs=pstmt.getGeneratedKeys();
                rs.next();
                int lastInsertedId=rs.getInt(1);
                pstmt=conn.prepareStatement("Insert Into Staff (staffId,salary) values(?,?)");
                pstmt.setInt(1, lastInsertedId);
                pstmt.setDouble(2, salary);
                pstmt.executeUpdate();
                pstmt=conn.prepareStatement("Insert Into Admin (staffId) values(?)");
                pstmt.setInt(1, lastInsertedId);
                pstmt.executeUpdate();
 
                rs.close();
                pstmt.close();
                conn.close();
            } catch (SQLException e) {
                System.out.println(e);
            }
             fetchFromTable();
            idTextField.setText("");
            fullNameTextField.setText("");
            phoneNoTextField.setText("");
            salaryTextField.setText("");
            passwordTextField.setText("12345678");
            ageTextField.setText("");
            maleRadiButton.setSelected(false);
            femaleRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void adminsTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminsTableKeyPressed

    }//GEN-LAST:event_adminsTableKeyPressed

    private void adminsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminsTableMouseClicked
        // TODO add your handling code here:
        int row = adminsTable.getSelectedRow();
        if(row>=0){
            String id=(String)adminsTable.getValueAt(row, 0);
            String name=(String)adminsTable.getValueAt(row, 1);
            String age=String.valueOf(adminsTable.getValueAt(row, 2));
            String gender=(String)adminsTable.getValueAt(row, 3);
            String phoneNo=(String)adminsTable.getValueAt(row, 4);
            String password=(String)adminsTable.getValueAt(row, 5);
            String salary=String.valueOf(adminsTable.getValueAt(row, 6));
            idTextField.setText(id);
            fullNameTextField.setText(name);
            ageTextField.setText(String.valueOf(age));
            if(gender.equals("Male")){
                maleRadiButton.setSelected(true);
            }else{
                femaleRadioButton.setSelected(true);
            }
            passwordTextField.setText(password);
            phoneNoTextField.setText(phoneNo);
            salaryTextField.setText(salary);
            }
    }//GEN-LAST:event_adminsTableMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = adminsTable.getSelectedRow();
        if (selectedRow >= 0) {
             String id = (String)adminsTable.getValueAt(selectedRow, 0);
            int result=JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the admin with id "+id+"?","Are you sure you want to delete the Admin?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
              id=id.substring(1, 5);
             int deletId=Integer.parseInt(id);
                if(result==JOptionPane.YES_OPTION){
                    try {
                        String url = "jdbc:mysql://localhost:3306/HMS_DB";
                        String username = "mahnat";
                        String passwordDB = "mahnat2023";
                        conn = DriverManager.getConnection(url, username, passwordDB);
                        pstmt=conn.prepareStatement("delete from Admin where staffId=?");
                        pstmt.setInt(1, deletId);
                        pstmt.executeUpdate();
                        pstmt=conn.prepareStatement("delete from Staff where staffId=?");
                        pstmt.setInt(1, deletId);
                        pstmt.executeUpdate();
                        pstmt=conn.prepareStatement("delete from Person where personId=?");
                        pstmt.setInt(1, deletId);
                        pstmt.executeUpdate();
                        pstmt.close();
                        conn.close();
                         
                }catch (SQLException e) {
                        System.out.println(e);
                     }
                    fetchFromTable();
                    idTextField.setText("");
                    fullNameTextField.setText("");
                    phoneNoTextField.setText("");
                    salaryTextField.setText("");
                    passwordTextField.setText("12345678");
                    ageTextField.setText("");
                    maleRadiButton.setSelected(false);
                    femaleRadioButton.setSelected(false);
            } 

        } else {
            JOptionPane.showMessageDialog(this, "No rows selected please select a row from the table!!.", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void searchTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextFieldKeyReleased
        // TODO add your handling code here:
         if (searchTextField.getText().length() != 0) {
            try {
                 String url = "jdbc:mysql://localhost:3306/HMS_DB";
                 String username = "mahnat";
                 String passwordDB = "mahnat2023";
                 conn = DriverManager.getConnection(url, username, passwordDB);
                String searchText = searchTextField.getText();
                String idPattern = "A\\d{4}/15";
                
                if(searchText.matches(idPattern)){
                    String query = "SELECT A.staffId,P.name,P.age,P.gender,P.phone,P.password,S.salary FROM Person P join Staff S on P.personId=S.staffID join Admin A on S.staffId=A.staffId WHERE A.staffId LIKE (?);";
                    pstmt=conn.prepareStatement(query);
                    pstmt.setInt(1, Integer.parseInt(searchText.substring(1, 5)));
                    rs = pstmt.executeQuery();
                }else{
                     String query = "SELECT A.staffId,P.name,P.age,P.gender,P.phone,P.password,S.salary FROM Person P join Staff S on P.personId=S.staffID join Admin A on S.staffId=A.staffId WHERE P.name LIKE (?) or A.staffId LIKE (?) or P.phone like (?);";
                    pstmt=conn.prepareStatement(query);
                    pstmt.setString(1, searchText+"%");
                    pstmt.setString(2, searchText+"%");
                    pstmt.setString(3, searchText+"%");
                    rs = pstmt.executeQuery();
                }
               
                
                
               DefaultTableModel model = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Make all cells non-editable
                }
                };
                model.addColumn("Id");
                model.addColumn("FullName");
                model.addColumn("Age");
                model.addColumn("Gender");
                model.addColumn("Phone no");
                model.addColumn("Password");
                model.addColumn("Salary");

            while (rs.next()) {
                int id=rs.getInt(1);
                String adminId="";
                if (id < 10) {
                    adminId += "A000" + id + "/15";
                } else if (id < 100 && id >= 10) {
                    adminId += "A00" + id + "/15";
                } else if (id < 1000 && id >= 100) {
                    adminId += "A0" + id + "/15";
                }
                String name=rs.getString(2);
                int age=rs.getInt(3);
                String gender=rs.getString(4);
                String phoneNo=rs.getString(5);
                String password=rs.getString(6);
                double salary=rs.getDouble(7);
                model.addRow(new Object[]{adminId, name, age, gender,phoneNo,password,salary});
                }
                
                adminsTable.setModel(model);
                rs.close();
                pstmt.close();
                conn.close();
            } catch (SQLException e) {
                System.out.println(e);
            }
        } else {
                fetchFromTable();
            
        }
    }//GEN-LAST:event_searchTextFieldKeyReleased
    
    public void fetchFromTable() {
        try {
             String url = "jdbc:mysql://localhost:3306/HMS_DB";
             String username = "mahnat";
             String passwordDB = "mahnat2023";
            conn = DriverManager.getConnection(url, username, passwordDB);
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT A.staffId,P.name,P.age,P.gender,P.phone,P.password,S.salary FROM Person P join Staff S on P.personId=S.staffID join Admin A on S.staffId=A.staffId;");

            DefaultTableModel model = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Make all cells non-editable
                }
            };
            model.addColumn("Id");
            model.addColumn("FullName");
            model.addColumn("Age");
            model.addColumn("Gender");
            model.addColumn("Phone no");
            model.addColumn("Password");
            model.addColumn("Salary");

        while (rs.next()) {
            int id=rs.getInt(1);
            String adminId="";
            if (id < 10) {
                adminId += "A000" + id + "/15";
            } else if (id < 100 && id >= 10) {
                adminId += "A00" + id + "/15";
            } else if (id < 1000 && id >= 100) {
                adminId += "A0" + id + "/15";
            }
            String name=rs.getString(2);
            int age=rs.getInt(3);
            String gender=rs.getString(4);
            String phoneNo=rs.getString(5);
            String password=rs.getString(6);
            double salary=rs.getDouble(7);
            model.addRow(new Object[]{adminId, name, age, gender,phoneNo,password,salary});
        }

        adminsTable.setModel(model);

        rs.close();
        stmt.close();
        conn.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.CustomStyle.MyButton addButton;
    private javax.swing.JTable adminsTable;
    private javax.swing.JTextField ageTextField;
    private GUI.CustomStyle.Panel content;
    private GUI.CustomStyle.MyButton deleteButton;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JLabel fullname_placeholder2;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maleRadiButton;
    private ButtonGroup sexGroup;
    private GUI.CustomStyle.MyButton newButton;
    private GUI.CustomStyle.Panel panel1;
    private GUI.CustomStyle.Panel panel11;
    private GUI.CustomStyle.Panel panel12;
    private GUI.CustomStyle.Panel panel13;
    private GUI.CustomStyle.Panel panel14;
    private GUI.CustomStyle.Panel panel15;
    private GUI.CustomStyle.Panel panel16;
    private GUI.CustomStyle.Panel panel18;
    private GUI.CustomStyle.Panel panel19;
    private GUI.CustomStyle.Panel panel21;
    private GUI.CustomStyle.Panel panel6;
    private GUI.CustomStyle.Panel panel7;
    private GUI.CustomStyle.Panel panel8;
    private GUI.CustomStyle.Panel panel9;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField phoneNoTextField;
    private javax.swing.JTextField salaryTextField;
    private javax.swing.JTextField searchTextField;
    private GUI.CustomStyle.MyButton updateButton;
    // End of variables declaration//GEN-END:variables
}
