package GUI.DoctorSide;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import GUI.HMS_Demo;
import GUI.LoginPanel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Doctor_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Admin_Emp
     */
    public Doctor_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel1 = new GUI.CustomStyle.Panel();
        Admin_emp_left = new GUI.CustomStyle.Panel();
        sideBar_paint1 = new GUI.AdminSide.SideBar_paint();
        jLabel4 = new javax.swing.JLabel();
        btn_Schedule = new GUI.CustomStyle.MyButton();
        panel2 = new GUI.CustomStyle.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_Prescribe = new GUI.CustomStyle.MyButton();
        jLabel8 = new javax.swing.JLabel();
        btn_DoctorNotific = new GUI.CustomStyle.MyButton();
        jLabel9 = new javax.swing.JLabel();
        btn_DoctorChangePass = new GUI.CustomStyle.MyButton();
        jLabel3 = new javax.swing.JLabel();
        btn_logOut = new GUI.CustomStyle.MyButton();
        btn_DiagnosisInfo = new GUI.CustomStyle.MyButton();
        jLabel12 = new javax.swing.JLabel();
        btn_DoctorMessage = new GUI.CustomStyle.MyButton();
        Admin_right_panel1 = new GUI.CustomStyle.Panel();
        Admin_Owner_jTabbedPane = new javax.swing.JTabbedPane();
        panel1 = new GUI.CustomStyle.Panel();
        appointment_Schedule1 = new GUI.DoctorSide.Appointment_Schedule();
        panel3 = new GUI.CustomStyle.Panel();
        prescribe_medical1 = new GUI.DoctorSide.Prescribe_medical();
        panel4 = new GUI.CustomStyle.Panel();
        patient_diagnosisInfo1 = new GUI.DoctorSide.Patient_diagnosisInfo();
        panel7 = new GUI.CustomStyle.Panel();
        doctor_Messages1 = new GUI.DoctorSide.Doctor_Messages();
        panel5 = new GUI.CustomStyle.Panel();
        doctor_Notification1 = new GUI.DoctorSide.Doctor_Notification();
        panel6 = new GUI.CustomStyle.Panel();
        doctor_Password1 = new GUI.DoctorSide.doctor_Password();

        setMinimumSize(new java.awt.Dimension(1300, 794));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1300, 794));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel1.setBackground(new java.awt.Color(0, 51, 51));
        mainPanel1.setMinimumSize(new java.awt.Dimension(1300, 794));
        mainPanel1.setPreferredSize(new java.awt.Dimension(1300, 794));
        mainPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admin_emp_left.setBackground(new java.awt.Color(0, 51, 51));
        Admin_emp_left.setToolTipText("");
        Admin_emp_left.setMinimumSize(new java.awt.Dimension(220, 790));
        Admin_emp_left.setName(""); // NOI18N
        Admin_emp_left.setOpaque(true);
        Admin_emp_left.setPreferredSize(new java.awt.Dimension(220, 790));
        Admin_emp_left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBar_paint1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/appointment.png"))); // NOI18N
        sideBar_paint1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 50, 40));

        btn_Schedule.setBackground(new java.awt.Color(153, 0, 153));
        btn_Schedule.setBorder(null);
        btn_Schedule.setForeground(new java.awt.Color(204, 255, 255));
        btn_Schedule.setText("Schedule");
        btn_Schedule.setAutoscrolls(true);
        btn_Schedule.setBorderColor(new java.awt.Color(153, 0, 153));
        btn_Schedule.setColor(new java.awt.Color(153, 0, 153));
        btn_Schedule.setColorClick(new java.awt.Color(77, 0, 102));
        btn_Schedule.setColorOver(new java.awt.Color(0, 132, 202));
        btn_Schedule.setFocusPainted(false);
        btn_Schedule.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Schedule.setMargin(new java.awt.Insets(2, 2, 3, 14));
        btn_Schedule.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_ScheduleMouseMoved(evt);
            }
        });
        btn_Schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ScheduleMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ScheduleMouseExited(evt);
            }
        });
        btn_Schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ScheduleActionPerformed(evt);
            }
        });
        sideBar_paint1.add(btn_Schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, 40));

        panel2.setBackground(new java.awt.Color(51, 51, 51));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dr.Username");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doctor_logo.png"))); // NOI18N
        panel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 139, 131));

        sideBar_paint1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 160));

        jLabel14.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 255));
        jLabel14.setText("My Data");
        sideBar_paint1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 60, 20));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/diagnosis.png"))); // NOI18N
        sideBar_paint1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 50, 40));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/medical-record.png"))); // NOI18N
        sideBar_paint1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 50, 40));

        btn_Prescribe.setBackground(new java.awt.Color(153, 0, 153));
        btn_Prescribe.setBorder(null);
        btn_Prescribe.setForeground(new java.awt.Color(204, 255, 255));
        btn_Prescribe.setText("Prescribe");
        btn_Prescribe.setBorderColor(new java.awt.Color(153, 0, 153));
        btn_Prescribe.setColor(new java.awt.Color(153, 0, 153));
        btn_Prescribe.setColorClick(new java.awt.Color(77, 0, 102));
        btn_Prescribe.setColorOver(new java.awt.Color(0, 132, 202));
        btn_Prescribe.setFocusPainted(false);
        btn_Prescribe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Prescribe.setMargin(new java.awt.Insets(2, 2, 3, 14));
        btn_Prescribe.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_PrescribeMouseMoved(evt);
            }
        });
        btn_Prescribe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_PrescribeMouseExited(evt);
            }
        });
        btn_Prescribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrescribeActionPerformed(evt);
            }
        });
        sideBar_paint1.add(btn_Prescribe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 40));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/push-notification.png"))); // NOI18N
        sideBar_paint1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 50, 40));

        btn_DoctorNotific.setBackground(new java.awt.Color(153, 0, 153));
        btn_DoctorNotific.setBorder(null);
        btn_DoctorNotific.setForeground(new java.awt.Color(204, 255, 255));
        btn_DoctorNotific.setText(" Notification");
        btn_DoctorNotific.setBorderColor(new java.awt.Color(153, 0, 153));
        btn_DoctorNotific.setColor(new java.awt.Color(153, 0, 153));
        btn_DoctorNotific.setColorClick(new java.awt.Color(77, 0, 102));
        btn_DoctorNotific.setColorOver(new java.awt.Color(0, 132, 202));
        btn_DoctorNotific.setFocusPainted(false);
        btn_DoctorNotific.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_DoctorNotific.setMargin(new java.awt.Insets(2, 2, 3, 14));
        btn_DoctorNotific.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_DoctorNotificMouseMoved(evt);
            }
        });
        btn_DoctorNotific.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DoctorNotificMouseExited(evt);
            }
        });
        btn_DoctorNotific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoctorNotificActionPerformed(evt);
            }
        });
        sideBar_paint1.add(btn_DoctorNotific, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 220, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset-password.png"))); // NOI18N
        sideBar_paint1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, 40));

        btn_DoctorChangePass.setBackground(new java.awt.Color(153, 0, 153));
        btn_DoctorChangePass.setBorder(null);
        btn_DoctorChangePass.setForeground(new java.awt.Color(204, 255, 255));
        btn_DoctorChangePass.setText("Change Password");
        btn_DoctorChangePass.setBorderColor(new java.awt.Color(153, 0, 153));
        btn_DoctorChangePass.setColor(new java.awt.Color(153, 0, 153));
        btn_DoctorChangePass.setColorClick(new java.awt.Color(77, 0, 102));
        btn_DoctorChangePass.setColorOver(new java.awt.Color(0, 132, 202));
        btn_DoctorChangePass.setFocusPainted(false);
        btn_DoctorChangePass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_DoctorChangePass.setMargin(new java.awt.Insets(2, 2, 3, 14));
        btn_DoctorChangePass.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_DoctorChangePassMouseMoved(evt);
            }
        });
        btn_DoctorChangePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DoctorChangePassMouseExited(evt);
            }
        });
        btn_DoctorChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoctorChangePassActionPerformed(evt);
            }
        });
        sideBar_paint1.add(btn_DoctorChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 220, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout (1).png"))); // NOI18N
        sideBar_paint1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 30, 40));

        btn_logOut.setBackground(new java.awt.Color(153, 0, 153));
        btn_logOut.setBorder(null);
        btn_logOut.setForeground(new java.awt.Color(255, 255, 255));
        btn_logOut.setText("LoginOut");
        btn_logOut.setBorderColor(new java.awt.Color(0, 102, 204));
        btn_logOut.setColor(new java.awt.Color(153, 0, 153));
        btn_logOut.setColorClick(new java.awt.Color(153, 0, 153));
        btn_logOut.setColorOver(new java.awt.Color(153, 11, 112));
        btn_logOut.setFocusPainted(false);
        btn_logOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_logOut.setRadius(25);
        btn_logOut.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_logOutMouseMoved(evt);
            }
        });
        btn_logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logOutActionPerformed(evt);
            }
        });
        sideBar_paint1.add(btn_logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 140, 40));

        btn_DiagnosisInfo.setBackground(new java.awt.Color(153, 0, 153));
        btn_DiagnosisInfo.setBorder(null);
        btn_DiagnosisInfo.setForeground(new java.awt.Color(204, 255, 255));
        btn_DiagnosisInfo.setText("Patient Diagnosis");
        btn_DiagnosisInfo.setBorderColor(new java.awt.Color(153, 0, 153));
        btn_DiagnosisInfo.setColor(new java.awt.Color(153, 0, 153));
        btn_DiagnosisInfo.setColorClick(new java.awt.Color(77, 0, 102));
        btn_DiagnosisInfo.setColorOver(new java.awt.Color(0, 132, 202));
        btn_DiagnosisInfo.setFocusPainted(false);
        btn_DiagnosisInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_DiagnosisInfo.setMargin(new java.awt.Insets(2, 2, 3, 14));
        btn_DiagnosisInfo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_DiagnosisInfoMouseMoved(evt);
            }
        });
        btn_DiagnosisInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DiagnosisInfoMouseExited(evt);
            }
        });
        btn_DiagnosisInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DiagnosisInfoActionPerformed(evt);
            }
        });
        sideBar_paint1.add(btn_DiagnosisInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 40));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/messages.png"))); // NOI18N
        sideBar_paint1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 50, 40));

        btn_DoctorMessage.setBackground(new java.awt.Color(153, 0, 153));
        btn_DoctorMessage.setBorder(null);
        btn_DoctorMessage.setForeground(new java.awt.Color(204, 255, 255));
        btn_DoctorMessage.setText("Messages");
        btn_DoctorMessage.setBorderColor(new java.awt.Color(153, 0, 153));
        btn_DoctorMessage.setColor(new java.awt.Color(153, 0, 153));
        btn_DoctorMessage.setColorClick(new java.awt.Color(77, 0, 102));
        btn_DoctorMessage.setColorOver(new java.awt.Color(0, 132, 202));
        btn_DoctorMessage.setFocusPainted(false);
        btn_DoctorMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_DoctorMessage.setMargin(new java.awt.Insets(2, 2, 3, 14));
        btn_DoctorMessage.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_DoctorMessageMouseMoved(evt);
            }
        });
        btn_DoctorMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DoctorMessageMouseExited(evt);
            }
        });
        btn_DoctorMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoctorMessageActionPerformed(evt);
            }
        });
        sideBar_paint1.add(btn_DoctorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 220, 40));

        Admin_emp_left.add(sideBar_paint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 6, 220, 750));

        mainPanel1.add(Admin_emp_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        Admin_right_panel1.setBackground(new java.awt.Color(0, 51, 51));
        Admin_right_panel1.setForeground(new java.awt.Color(51, 51, 51));
        Admin_right_panel1.setMinimumSize(new java.awt.Dimension(900, 788));
        Admin_right_panel1.setName(""); // NOI18N
        Admin_right_panel1.setPreferredSize(new java.awt.Dimension(900, 788));
        Admin_right_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admin_Owner_jTabbedPane.setBackground(new java.awt.Color(51, 51, 51));
        Admin_Owner_jTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        Admin_Owner_jTabbedPane.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        Admin_Owner_jTabbedPane.setPreferredSize(new java.awt.Dimension(150, 730));

        panel1.setBackground(new java.awt.Color(0, 51, 51));
        panel1.setForeground(new java.awt.Color(51, 51, 51));
        panel1.setMinimumSize(new java.awt.Dimension(1080, 839));
        panel1.setName(""); // NOI18N

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(appointment_Schedule1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(appointment_Schedule1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        Admin_Owner_jTabbedPane.addTab("tab6", panel1);

        panel3.setBackground(new java.awt.Color(0, 51, 51));
        panel3.setForeground(new java.awt.Color(51, 51, 51));
        panel3.setMinimumSize(new java.awt.Dimension(1028, 804));
        panel3.setOpaque(true);
        panel3.setPreferredSize(new java.awt.Dimension(1028, 804));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(prescribe_medical1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(prescribe_medical1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        Admin_Owner_jTabbedPane.addTab("tab6", panel3);

        panel4.setBackground(new java.awt.Color(0, 51, 51));
        panel4.setForeground(new java.awt.Color(51, 51, 51));
        panel4.setMinimumSize(new java.awt.Dimension(1028, 804));
        panel4.setOpaque(true);

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(patient_diagnosisInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(patient_diagnosisInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        Admin_Owner_jTabbedPane.addTab("tab6", panel4);

        panel7.setBackground(new java.awt.Color(0, 51, 51));

        doctor_Messages1.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
        panel7.setLayout(panel7Layout);
        panel7Layout.setHorizontalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(doctor_Messages1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        panel7Layout.setVerticalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(doctor_Messages1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        Admin_Owner_jTabbedPane.addTab("tab6", panel7);

        panel5.setBackground(new java.awt.Color(0, 51, 51));
        panel5.setForeground(new java.awt.Color(51, 51, 51));
        panel5.setMinimumSize(new java.awt.Dimension(1028, 804));

        doctor_Notification1.setOpaque(false);

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(doctor_Notification1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(383, Short.MAX_VALUE))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(doctor_Notification1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        Admin_Owner_jTabbedPane.addTab("tab6", panel5);

        panel6.setBackground(new java.awt.Color(0, 51, 51));
        panel6.setForeground(new java.awt.Color(51, 51, 51));
        panel6.setMinimumSize(new java.awt.Dimension(1028, 804));
        panel6.setOpaque(true);

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(doctor_Password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(604, Short.MAX_VALUE))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(doctor_Password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        Admin_Owner_jTabbedPane.addTab("tab6", panel6);

        Admin_right_panel1.add(Admin_Owner_jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 1150, 870));

        mainPanel1.add(Admin_right_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1110, 780));

        add(mainPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 770));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ScheduleMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ScheduleMouseMoved
        // TODO add your handling code here:
        btn_Schedule.setRadius(25);
        btn_Schedule.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_ScheduleMouseMoved

    private void btn_ScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ScheduleMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_ScheduleMouseClicked

    private void btn_ScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ScheduleActionPerformed
        // TODO add your handling code here:
        HMS_Demo.sizeFrame(1300, 794);
        Admin_Owner_jTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_btn_ScheduleActionPerformed

    private void btn_PrescribeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PrescribeMouseMoved
        // TODO add your handling code here:
        btn_Prescribe.setRadius(25);
        btn_Prescribe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_PrescribeMouseMoved

    private void btn_PrescribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrescribeActionPerformed
        // TODO add your handling code here:
         HMS_Demo.sizeFrame(1300, 794);
        Admin_Owner_jTabbedPane.setSelectedIndex(1);
        
    }//GEN-LAST:event_btn_PrescribeActionPerformed

    private void btn_DoctorNotificMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DoctorNotificMouseMoved
        // TODO add your handling code here:
        btn_DoctorNotific.setRadius(25);
        btn_DoctorNotific.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_DoctorNotificMouseMoved

    private void btn_DoctorNotificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoctorNotificActionPerformed
        // TODO add your handling code here:
        HMS_Demo.sizeFrame(1020, 794);
        Admin_Owner_jTabbedPane.setSelectedIndex(4);
    }//GEN-LAST:event_btn_DoctorNotificActionPerformed

    private void btn_DoctorChangePassMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DoctorChangePassMouseMoved
        // TODO add your handling code here:
        btn_DoctorChangePass.setRadius(25);
        btn_DoctorChangePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_DoctorChangePassMouseMoved

    private void btn_DoctorChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoctorChangePassActionPerformed
        // TODO add your handling code here:
         HMS_Demo.sizeFrame(780, 794);
        Admin_Owner_jTabbedPane.setSelectedIndex(5);
    }//GEN-LAST:event_btn_DoctorChangePassActionPerformed

    private void btn_logOutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logOutMouseMoved
        // TODO add your handling code here:
        btn_logOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_logOutMouseMoved

    private void btn_logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logOutActionPerformed
        // TODO add your handling code here:
        int result=JOptionPane.showConfirmDialog(this, "Are you sure you want to log out from the HMS?","Are you sure you want to log out?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
    if(result==JOptionPane.YES_OPTION){
             HMS_Demo.switchPanel(new LoginPanel());
         } 
          HMS_Demo.sizeFrame(1300, 794);
        HMS_Demo.switchPanel(new LoginPanel());
    }//GEN-LAST:event_btn_logOutActionPerformed

    private void btn_ScheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ScheduleMouseExited
        // TODO add your handling code here:
        btn_Schedule.setRadius(0);
    }//GEN-LAST:event_btn_ScheduleMouseExited

    private void btn_PrescribeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PrescribeMouseExited
        // TODO add your handling code here:
        btn_Prescribe.setRadius(0);
    }//GEN-LAST:event_btn_PrescribeMouseExited

    private void btn_DoctorNotificMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DoctorNotificMouseExited
        // TODO add your handling code here:
         btn_DoctorNotific.setRadius(0);
    }//GEN-LAST:event_btn_DoctorNotificMouseExited

    private void btn_DoctorChangePassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DoctorChangePassMouseExited
        // TODO add your handling code here:
         btn_DoctorChangePass.setRadius(0);
    }//GEN-LAST:event_btn_DoctorChangePassMouseExited

    private void btn_DiagnosisInfoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DiagnosisInfoMouseMoved
        // TODO add your handling code here:
         btn_DiagnosisInfo.setRadius(25);
        btn_DiagnosisInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_DiagnosisInfoMouseMoved

    private void btn_DiagnosisInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DiagnosisInfoMouseExited
        // TODO add your handling code here:
        btn_DiagnosisInfo.setRadius(0);
    }//GEN-LAST:event_btn_DiagnosisInfoMouseExited

    private void btn_DiagnosisInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DiagnosisInfoActionPerformed
        // TODO add your handling code here:
         HMS_Demo.sizeFrame(1300, 794);
         Admin_Owner_jTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_btn_DiagnosisInfoActionPerformed

    private void btn_DoctorMessageMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DoctorMessageMouseMoved
        // TODO add your handling code here:
         btn_DoctorMessage.setRadius(25);
        btn_DoctorMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
 
    }//GEN-LAST:event_btn_DoctorMessageMouseMoved

    private void btn_DoctorMessageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DoctorMessageMouseExited
        // TODO add your handling code here:
         btn_DoctorMessage.setRadius(0);
    }//GEN-LAST:event_btn_DoctorMessageMouseExited

    private void btn_DoctorMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoctorMessageActionPerformed
        // TODO add your handling code here:
         HMS_Demo.sizeFrame(1180, 794);
        Admin_Owner_jTabbedPane.setSelectedIndex(3);
    }//GEN-LAST:event_btn_DoctorMessageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Admin_Owner_jTabbedPane;
    private GUI.CustomStyle.Panel Admin_emp_left;
    private GUI.CustomStyle.Panel Admin_right_panel1;
    private GUI.DoctorSide.Appointment_Schedule appointment_Schedule1;
    private GUI.CustomStyle.MyButton btn_DiagnosisInfo;
    private GUI.CustomStyle.MyButton btn_DoctorChangePass;
    private GUI.CustomStyle.MyButton btn_DoctorMessage;
    private GUI.CustomStyle.MyButton btn_DoctorNotific;
    private GUI.CustomStyle.MyButton btn_Prescribe;
    private GUI.CustomStyle.MyButton btn_Schedule;
    private GUI.CustomStyle.MyButton btn_logOut;
    private GUI.DoctorSide.Doctor_Messages doctor_Messages1;
    private GUI.DoctorSide.Doctor_Notification doctor_Notification1;
    private GUI.DoctorSide.doctor_Password doctor_Password1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private GUI.CustomStyle.Panel mainPanel1;
    private GUI.CustomStyle.Panel panel1;
    private GUI.CustomStyle.Panel panel2;
    private GUI.CustomStyle.Panel panel3;
    private GUI.CustomStyle.Panel panel4;
    private GUI.CustomStyle.Panel panel5;
    private GUI.CustomStyle.Panel panel6;
    private GUI.CustomStyle.Panel panel7;
    private GUI.DoctorSide.Patient_diagnosisInfo patient_diagnosisInfo1;
    private GUI.DoctorSide.Prescribe_medical prescribe_medical1;
    private GUI.AdminSide.SideBar_paint sideBar_paint1;
    // End of variables declaration//GEN-END:variables
}
