/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.DoctorSide;

import GUI.ReceptionistSide.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.JTableHeader;

/**
 *
 * @author HP
 */
public class Prescribe_medical extends javax.swing.JPanel {

    private Connection conn;
    private Statement stmt;
    private PreparedStatement pstmt;
    private ResultSet rs;
    /**
     * Creates new form AdminEmployeed
     */
    public Prescribe_medical() {
        initComponents();
          JTableHeader tableHeader=AppointedTable.getTableHeader();
        tableHeader.setForeground(new Color(204,255,255));
        tableHeader.setBackground(new Color(82,2,31));
         JTableHeader tableHeader2=prescribedtable.getTableHeader();
        tableHeader2.setForeground(new Color(204,255,255));
        tableHeader2.setBackground(new Color(82,2,31));
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/HMS_DB";
        String username = "mahnat";
        String password = "mahnat2023";
        conn = DriverManager.getConnection(url, username, password);

        stmt = conn.createStatement();
        String createTableQuery="CREATE TABLE if not exists Prescription (\n" +
                                "  prescriptionId int auto_increment PRIMARY KEY,\n" +
                                "  doctorId int,\n" +
                                "  patientId int,\n" +
                                "  date DATE,\n" +
                                "  medicineName VARCHAR(50),\n" +
                                "  doseOfMedicine INT,\n" +
                                "  duration INT,\n" +
                                "  FOREIGN KEY (doctorId) REFERENCES Doctor(doctorId),\n" +
                                "  FOREIGN KEY (patientId) REFERENCES Patient(patientId)\n" +
                                ");";
        stmt.executeUpdate(createTableQuery);    
           
       
        stmt.close();
        conn.close();
        }catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
        }
//         fetchToAppointmedList();
//         fetchToPrescribedList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new GUI.CustomStyle.Panel();
        jLabel8 = new javax.swing.JLabel();
        panel6 = new GUI.CustomStyle.Panel();
        jLabel1 = new javax.swing.JLabel();
        panel7 = new GUI.CustomStyle.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prescribedtable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        AppointedTable = new javax.swing.JTable();
        panel3 = new GUI.CustomStyle.Panel();
        jLabel11 = new javax.swing.JLabel();
        panel4 = new GUI.CustomStyle.Panel();
        jLabel12 = new javax.swing.JLabel();
        panel8 = new GUI.CustomStyle.Panel();
        panel9 = new GUI.CustomStyle.Panel();
        jLabel3 = new javax.swing.JLabel();
        btn_New = new GUI.CustomStyle.MyButton();
        panel14 = new GUI.CustomStyle.Panel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panel11 = new GUI.CustomStyle.Panel();
        emp_Admin_fullname = new javax.swing.JTextField();
        panel12 = new GUI.CustomStyle.Panel();
        emp_Admin_username = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        panel13 = new GUI.CustomStyle.Panel();
        emp_Admin_password = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panel15 = new GUI.CustomStyle.Panel();
        emp_Admin_password1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        day_spin = new javax.swing.JSpinner();
        moonth_spin = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        year_spin = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(0, 51, 51));

        content.setBackground(new java.awt.Color(204, 255, 255));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/prescription2.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        content.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, -1));

        panel6.setBackground(new java.awt.Color(20, 9, 148));
        panel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Medical Prescription");
        panel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 200, 40));

        content.add(panel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 280, 40));

        panel7.setBackground(new java.awt.Color(255, 204, 204));

        prescribedtable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prescribedtable.setForeground(new java.awt.Color(51, 51, 51));
        prescribedtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Presc_ID", "PatientID", "PatientName", "Date", "MedicineName", "Dose", "Duration"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        prescribedtable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prescribedtable.setEditingColumn(0);
        prescribedtable.setEditingRow(0);
        prescribedtable.setFocusable(false);
        prescribedtable.setGridColor(new java.awt.Color(204, 204, 255));
        prescribedtable.setOpaque(false);
        prescribedtable.setRowHeight(25);
        prescribedtable.setSelectionBackground(new java.awt.Color(255, 239, 235));
        prescribedtable.setSelectionForeground(new java.awt.Color(0, 51, 255));
        jScrollPane1.setViewportView(prescribedtable);

        AppointedTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AppointedTable.setForeground(new java.awt.Color(51, 51, 51));
        AppointedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PatientName", "Patient Id", "LocalDate", "Localtime"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        AppointedTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AppointedTable.setEditingColumn(0);
        AppointedTable.setEditingRow(0);
        AppointedTable.setFocusable(false);
        AppointedTable.setGridColor(new java.awt.Color(204, 204, 255));
        AppointedTable.setOpaque(false);
        AppointedTable.setRowHeight(25);
        AppointedTable.setSelectionBackground(new java.awt.Color(255, 239, 235));
        AppointedTable.setSelectionForeground(new java.awt.Color(0, 51, 255));
        jScrollPane2.setViewportView(AppointedTable);

        panel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Appointed PatientList");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel3Layout.createSequentialGroup()
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PrescriptionTable");

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
        panel7.setLayout(panel7Layout);
        panel7Layout.setHorizontalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel7Layout.createSequentialGroup()
                .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel7Layout.createSequentialGroup()
                        .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel7Layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel7Layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 235, Short.MAX_VALUE))
                    .addGroup(panel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        panel7Layout.setVerticalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        content.add(panel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 730, 580));

        panel8.setBackground(new java.awt.Color(255, 204, 204));
        panel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel9.setBackground(new java.awt.Color(82, 2, 31));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Prescription");

        javax.swing.GroupLayout panel9Layout = new javax.swing.GroupLayout(panel9);
        panel9.setLayout(panel9Layout);
        panel9Layout.setHorizontalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel9Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel9Layout.setVerticalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel8.add(panel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));

        btn_New.setBackground(new java.awt.Color(23, 169, 232));
        btn_New.setBorder(null);
        btn_New.setForeground(new java.awt.Color(255, 255, 255));
        btn_New.setText("PRESCRIBE");
        btn_New.setBorderColor(new java.awt.Color(255, 204, 204));
        btn_New.setColor(new java.awt.Color(23, 169, 232));
        btn_New.setColorClick(new java.awt.Color(23, 133, 232));
        btn_New.setColorOver(new java.awt.Color(0, 133, 218));
        btn_New.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_New.setRadius(20);
        btn_New.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_NewMouseMoved(evt);
            }
        });
        btn_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewActionPerformed(evt);
            }
        });
        panel8.add(btn_New, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 417, 150, 40));

        panel14.setBackground(new java.awt.Color(247, 247, 247));

        javax.swing.GroupLayout panel14Layout = new javax.swing.GroupLayout(panel14);
        panel14.setLayout(panel14Layout);
        panel14Layout.setHorizontalGroup(
            panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel14Layout.setVerticalGroup(
            panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel8.add(panel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("PatientID");
        panel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("PatientName");
        panel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, 20));

        panel11.setBackground(new java.awt.Color(247, 247, 247));
        panel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emp_Admin_fullname.setEditable(false);
        emp_Admin_fullname.setBackground(new java.awt.Color(247, 247, 247));
        emp_Admin_fullname.setBorder(null);
        emp_Admin_fullname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emp_Admin_fullname.setOpaque(true);
        emp_Admin_fullname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emp_Admin_fullnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emp_Admin_fullnameFocusLost(evt);
            }
        });
        panel11.add(emp_Admin_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));

        panel8.add(panel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 200, 30));

        panel12.setBackground(new java.awt.Color(247, 247, 247));
        panel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emp_Admin_username.setEditable(false);
        emp_Admin_username.setBackground(new java.awt.Color(247, 247, 247));
        emp_Admin_username.setBorder(null);
        emp_Admin_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emp_Admin_username.setOpaque(true);
        emp_Admin_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emp_Admin_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emp_Admin_usernameFocusLost(evt);
            }
        });
        panel12.add(emp_Admin_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));

        panel8.add(panel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 0));
        jLabel9.setText("Date");
        panel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 60, 20));

        panel13.setBackground(new java.awt.Color(247, 247, 247));
        panel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emp_Admin_password.setBackground(new java.awt.Color(247, 247, 247));
        emp_Admin_password.setBorder(null);
        emp_Admin_password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emp_Admin_password.setOpaque(true);
        emp_Admin_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emp_Admin_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emp_Admin_passwordFocusLost(evt);
            }
        });
        panel13.add(emp_Admin_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));

        panel8.add(panel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 200, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setText("Duration");
        panel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 60, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 0));
        jLabel10.setText("DoseOfMedicine");
        panel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 20));

        panel15.setBackground(new java.awt.Color(247, 247, 247));
        panel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emp_Admin_password1.setBackground(new java.awt.Color(247, 247, 247));
        emp_Admin_password1.setBorder(null);
        emp_Admin_password1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emp_Admin_password1.setOpaque(true);
        emp_Admin_password1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emp_Admin_password1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emp_Admin_password1FocusLost(evt);
            }
        });
        panel15.add(emp_Admin_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));

        panel8.add(panel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 0));
        jLabel16.setText("Day");
        panel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 40, 20));
        panel8.add(day_spin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 70, -1));
        panel8.add(moonth_spin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 70, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 0, 0));
        jLabel17.setText("Month");
        panel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 40, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 0));
        jLabel14.setText("Year");
        panel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 40, 20));
        panel8.add(year_spin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 70, -1));

        content.add(panel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 240, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NewMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NewMouseMoved
        // TODO add your handling code here:
        btn_New.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_NewMouseMoved

    private void btn_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NewActionPerformed

    private void emp_Admin_fullnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emp_Admin_fullnameFocusGained

        //fullname_placeholder.setText("");
    }//GEN-LAST:event_emp_Admin_fullnameFocusGained

    private void emp_Admin_fullnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emp_Admin_fullnameFocusLost
//        // TODO add your handling code here:
//        fullname_placeholder.setForeground(new java.awt.Color(187,187,187));
//        fullname_placeholder.setFont(new java.awt.Font("Segoe UI", 0, 14));
//        fullname_placeholder.setText("fullname");
    }//GEN-LAST:event_emp_Admin_fullnameFocusLost

    private void emp_Admin_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emp_Admin_usernameFocusGained
        // TODO add your handling code here:
       // username_placeholder.setText("");
    }//GEN-LAST:event_emp_Admin_usernameFocusGained

    private void emp_Admin_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emp_Admin_usernameFocusLost
        // TODO add your handling code here:
//        username_placeholder.setForeground(new java.awt.Color(187,187,187));
//        username_placeholder.setFont(new java.awt.Font("Segoe UI", 0, 14));
//        username_placeholder.setText("username");
    }//GEN-LAST:event_emp_Admin_usernameFocusLost

    private void emp_Admin_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emp_Admin_passwordFocusGained
        // TODO add your handling code here:
       // password_placeholder.setText("");
    }//GEN-LAST:event_emp_Admin_passwordFocusGained

    private void emp_Admin_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emp_Admin_passwordFocusLost
        // TODO add your handling code here:
//        password_placeholder.setForeground(new java.awt.Color(187,187,187));
//        password_placeholder.setFont(new java.awt.Font("Segoe UI", 0, 14));
//        password_placeholder.setText("password");
    }//GEN-LAST:event_emp_Admin_passwordFocusLost

    private void emp_Admin_password1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emp_Admin_password1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_Admin_password1FocusGained

    private void emp_Admin_password1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emp_Admin_password1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_Admin_password1FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AppointedTable;
    private GUI.CustomStyle.MyButton btn_New;
    private GUI.CustomStyle.Panel content;
    private javax.swing.JSpinner day_spin;
    private javax.swing.JTextField emp_Admin_fullname;
    private javax.swing.JTextField emp_Admin_password;
    private javax.swing.JTextField emp_Admin_password1;
    private javax.swing.JTextField emp_Admin_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner moonth_spin;
    private GUI.CustomStyle.Panel panel11;
    private GUI.CustomStyle.Panel panel12;
    private GUI.CustomStyle.Panel panel13;
    private GUI.CustomStyle.Panel panel14;
    private GUI.CustomStyle.Panel panel15;
    private GUI.CustomStyle.Panel panel3;
    private GUI.CustomStyle.Panel panel4;
    private GUI.CustomStyle.Panel panel6;
    private GUI.CustomStyle.Panel panel7;
    private GUI.CustomStyle.Panel panel8;
    private GUI.CustomStyle.Panel panel9;
    private javax.swing.JTable prescribedtable;
    private javax.swing.JSpinner year_spin;
    // End of variables declaration//GEN-END:variables
}
